import { BaseSeeder } from '@adonisjs/lucid/seeders'
import City from '#models/city'

export default class extends BaseSeeder {
  async run() {
    // Check if cities already exist to avoid duplicates
    const existingCitiesCount = await City.query().count('* as total')
    if (Number(existingCitiesCount[0].$extras.total) > 0) {
      console.log('Cities already seeded, skipping...')
      return
    }

    const cities = [
      // Major French cities with real geographic and administrative data
      {
        name: 'Paris',
        slug: 'paris',
        postalCode: '75000',
        inseeCode: '75056',
        latitude: 48.8566,
        longitude: 2.3522,
        population: 2161000,
        area: 105.4,
        departmentCode: '75',
        departmentName: 'Paris',
        regionCode: '11',
        regionName: 'Île-de-France',
        description: 'Capitale de la France, centre culturel et économique majeur',
        metaTitle: 'Tatoueurs à Paris - Trouvez votre artiste tatoueur à Paris',
        metaDescription:
          'Découvrez les meilleurs tatoueurs de Paris. Réservez votre rendez-vous avec un artiste tatoueur qualifié dans la capitale.',
        seoKeywords: JSON.stringify(['tatoueur paris', 'tattoo paris', 'salon tatouage paris']),
        isActive: true,
        isFeatured: true,
        priority: 1,
      },
      {
        name: 'Marseille',
        slug: 'marseille',
        postalCode: '13000',
        inseeCode: '13055',
        latitude: 43.2965,
        longitude: 5.3698,
        population: 870000,
        area: 240.6,
        departmentCode: '13',
        departmentName: 'Bouches-du-Rhône',
        regionCode: '93',
        regionName: "Provence-Alpes-Côte d'Azur",
        description: 'Deuxième ville de France, port méditerranéen historique',
        metaTitle: 'Tatoueurs à Marseille - Studios de tatouage Marseille',
        metaDescription:
          'Trouvez les meilleurs tatoueurs de Marseille. Découvrez les studios de tatouage réputés dans la cité phocéenne.',
        seoKeywords: JSON.stringify([
          'tatoueur marseille',
          'tattoo marseille',
          'studio tatouage marseille',
        ]),
        isActive: true,
        isFeatured: true,
        priority: 2,
      },
      {
        name: 'Lyon',
        slug: 'lyon',
        postalCode: '69000',
        inseeCode: '69123',
        latitude: 45.764,
        longitude: 4.8357,
        population: 518000,
        area: 47.9,
        departmentCode: '69',
        departmentName: 'Rhône',
        regionCode: '84',
        regionName: 'Auvergne-Rhône-Alpes',
        description: 'Troisième ville de France, capitale de la gastronomie',
        metaTitle: 'Tatoueurs à Lyon - Meilleurs studios de tatouage Lyon',
        metaDescription:
          'Découvrez les tatoueurs lyonnais les plus talentueux. Réservez dans un studio de tatouage professionnel à Lyon.',
        seoKeywords: JSON.stringify(['tatoueur lyon', 'tattoo lyon', 'salon tatouage lyon']),
        isActive: true,
        isFeatured: true,
        priority: 3,
      },
      {
        name: 'Toulouse',
        slug: 'toulouse',
        postalCode: '31000',
        inseeCode: '31555',
        latitude: 43.6047,
        longitude: 1.4442,
        population: 479000,
        area: 118.3,
        departmentCode: '31',
        departmentName: 'Haute-Garonne',
        regionCode: '76',
        regionName: 'Occitanie',
        description: 'La ville rose, capitale aéronautique européenne',
        metaTitle: 'Tatoueurs à Toulouse - Studios tatouage Toulouse',
        metaDescription:
          'Trouvez votre tatoueur à Toulouse. Les meilleurs artistes tatoueurs de la ville rose vous attendent.',
        seoKeywords: JSON.stringify([
          'tatoueur toulouse',
          'tattoo toulouse',
          'studio tatouage toulouse',
        ]),
        isActive: true,
        isFeatured: true,
        priority: 4,
      },
      {
        name: 'Nice',
        slug: 'nice',
        postalCode: '06000',
        inseeCode: '06088',
        latitude: 43.7102,
        longitude: 7.262,
        population: 343000,
        area: 71.9,
        departmentCode: '06',
        departmentName: 'Alpes-Maritimes',
        regionCode: '93',
        regionName: "Provence-Alpes-Côte d'Azur",
        description: "Perle de la Côte d'Azur, destination touristique majeure",
        metaTitle: "Tatoueurs à Nice - Artistes tatoueurs Côte d'Azur",
        metaDescription:
          "Les meilleurs tatoueurs de Nice et de la Côte d'Azur. Réservez votre tatouage dans un studio professionnel.",
        seoKeywords: JSON.stringify(['tatoueur nice', 'tattoo nice', 'tatouage côte azur']),
        isActive: true,
        isFeatured: true,
        priority: 5,
      },
      {
        name: 'Nantes',
        slug: 'nantes',
        postalCode: '44000',
        inseeCode: '44109',
        latitude: 47.2184,
        longitude: -1.5536,
        population: 314000,
        area: 65.2,
        departmentCode: '44',
        departmentName: 'Loire-Atlantique',
        regionCode: '52',
        regionName: 'Pays de la Loire',
        description: 'Ancienne capitale bretonne, ville culturelle dynamique',
        metaTitle: 'Tatoueurs à Nantes - Studios de tatouage Nantes',
        metaDescription:
          'Découvrez les tatoueurs nantais. Trouvez votre artiste tatoueur dans un studio professionnel à Nantes.',
        seoKeywords: JSON.stringify(['tatoueur nantes', 'tattoo nantes', 'salon tatouage nantes']),
        isActive: true,
        isFeatured: true,
        priority: 6,
      },
      {
        name: 'Montpellier',
        slug: 'montpellier',
        postalCode: '34000',
        inseeCode: '34172',
        latitude: 43.611,
        longitude: 3.8767,
        population: 295000,
        area: 56.9,
        departmentCode: '34',
        departmentName: 'Hérault',
        regionCode: '76',
        regionName: 'Occitanie',
        description: 'Ville universitaire dynamique du sud de la France',
        metaTitle: 'Tatoueurs à Montpellier - Meilleurs studios tatouage',
        metaDescription:
          'Les tatoueurs les plus talentueux de Montpellier. Réservez votre rendez-vous dans un studio de tatouage reconnu.',
        seoKeywords: JSON.stringify([
          'tatoueur montpellier',
          'tattoo montpellier',
          'studio tatouage montpellier',
        ]),
        isActive: true,
        isFeatured: true,
        priority: 7,
      },
      {
        name: 'Strasbourg',
        slug: 'strasbourg',
        postalCode: '67000',
        inseeCode: '67482',
        latitude: 48.5734,
        longitude: 7.7521,
        population: 280000,
        area: 78.3,
        departmentCode: '67',
        departmentName: 'Bas-Rhin',
        regionCode: '44',
        regionName: 'Grand Est',
        description: 'Capitale européenne, ville frontalière franco-allemande',
        metaTitle: 'Tatoueurs à Strasbourg - Studios tatouage Strasbourg',
        metaDescription:
          'Trouvez les meilleurs tatoueurs strasbourgeois. Découvrez les studios de tatouage de qualité à Strasbourg.',
        seoKeywords: JSON.stringify([
          'tatoueur strasbourg',
          'tattoo strasbourg',
          'salon tatouage strasbourg',
        ]),
        isActive: true,
        isFeatured: false,
        priority: 10,
      },
      {
        name: 'Bordeaux',
        slug: 'bordeaux',
        postalCode: '33000',
        inseeCode: '33063',
        latitude: 44.8378,
        longitude: -0.5792,
        population: 257000,
        area: 49.4,
        departmentCode: '33',
        departmentName: 'Gironde',
        regionCode: '75',
        regionName: 'Nouvelle-Aquitaine',
        description: 'Capitale mondiale du vin, patrimoine UNESCO',
        metaTitle: 'Tatoueurs à Bordeaux - Artistes tatoueurs Bordeaux',
        metaDescription:
          'Les meilleurs tatoueurs de Bordeaux vous accueillent. Réservez dans un studio de tatouage professionnel.',
        seoKeywords: JSON.stringify([
          'tatoueur bordeaux',
          'tattoo bordeaux',
          'studio tatouage bordeaux',
        ]),
        isActive: true,
        isFeatured: true,
        priority: 8,
      },
      {
        name: 'Lille',
        slug: 'lille',
        postalCode: '59000',
        inseeCode: '59350',
        latitude: 50.6292,
        longitude: 3.0573,
        population: 232000,
        area: 34.5,
        departmentCode: '59',
        departmentName: 'Nord',
        regionCode: '32',
        regionName: 'Hauts-de-France',
        description: 'Capitale des Flandres, carrefour européen',
        metaTitle: 'Tatoueurs à Lille - Studios de tatouage Lille',
        metaDescription:
          'Découvrez les tatoueurs lillois les plus créatifs. Trouvez votre studio de tatouage idéal à Lille.',
        seoKeywords: JSON.stringify(['tatoueur lille', 'tattoo lille', 'salon tatouage lille']),
        isActive: true,
        isFeatured: false,
        priority: 9,
      },
      {
        name: 'Rennes',
        slug: 'rennes',
        postalCode: '35000',
        inseeCode: '35238',
        latitude: 48.1173,
        longitude: -1.6778,
        population: 217000,
        area: 50.4,
        departmentCode: '35',
        departmentName: 'Ille-et-Vilaine',
        regionCode: '53',
        regionName: 'Bretagne',
        description: 'Capitale bretonne, ville universitaire dynamique',
        metaTitle: 'Tatoueurs à Rennes - Meilleurs studios tatouage Rennes',
        metaDescription:
          'Les tatoueurs rennais les plus talentueux. Réservez votre tatouage dans un studio professionnel à Rennes.',
        seoKeywords: JSON.stringify(['tatoueur rennes', 'tattoo rennes', 'studio tatouage rennes']),
        isActive: true,
        isFeatured: false,
        priority: 11,
      },
      {
        name: 'Reims',
        slug: 'reims',
        postalCode: '51100',
        inseeCode: '51454',
        latitude: 49.2583,
        longitude: 4.0317,
        population: 182000,
        area: 46.9,
        departmentCode: '51',
        departmentName: 'Marne',
        regionCode: '44',
        regionName: 'Grand Est',
        description: 'Cité des rois, capitale du champagne',
        metaTitle: 'Tatoueurs à Reims - Studios tatouage Reims',
        metaDescription:
          'Trouvez votre tatoueur à Reims. Découvrez les studios de tatouage de la cité des sacres.',
        seoKeywords: JSON.stringify(['tatoueur reims', 'tattoo reims', 'salon tatouage reims']),
        isActive: true,
        isFeatured: false,
        priority: 15,
      },
      // Additional cities for better coverage
      {
        name: 'Le Havre',
        slug: 'le-havre',
        postalCode: '76600',
        inseeCode: '76351',
        latitude: 49.4944,
        longitude: 0.1079,
        population: 170000,
        area: 46.9,
        departmentCode: '76',
        departmentName: 'Seine-Maritime',
        regionCode: '28',
        regionName: 'Normandie',
        description: 'Port atlantique majeur, architecture moderne classée UNESCO',
        metaTitle: 'Tatoueurs au Havre - Studios de tatouage Le Havre',
        metaDescription:
          'Les meilleurs tatoueurs du Havre. Trouvez votre artiste tatoueur en Normandie.',
        seoKeywords: JSON.stringify([
          'tatoueur le havre',
          'tattoo le havre',
          'studio tatouage havre',
        ]),
        isActive: true,
        isFeatured: false,
        priority: 20,
      },
      {
        name: 'Saint-Étienne',
        slug: 'saint-etienne',
        postalCode: '42000',
        inseeCode: '42218',
        latitude: 45.4397,
        longitude: 4.3872,
        population: 172000,
        area: 79.7,
        departmentCode: '42',
        departmentName: 'Loire',
        regionCode: '84',
        regionName: 'Auvergne-Rhône-Alpes',
        description: 'Ville industrielle historique, patrimoine minier',
        metaTitle: 'Tatoueurs à Saint-Étienne - Studios tatouage Loire',
        metaDescription:
          'Découvrez les tatoueurs stéphanois. Réservez dans un studio de tatouage professionnel à Saint-Étienne.',
        seoKeywords: JSON.stringify([
          'tatoueur saint etienne',
          'tattoo saint etienne',
          'salon tatouage loire',
        ]),
        isActive: true,
        isFeatured: false,
        priority: 25,
      },
      {
        name: 'Toulon',
        slug: 'toulon',
        postalCode: '83000',
        inseeCode: '83137',
        latitude: 43.1242,
        longitude: 5.928,
        population: 176000,
        area: 42.8,
        departmentCode: '83',
        departmentName: 'Var',
        regionCode: '93',
        regionName: "Provence-Alpes-Côte d'Azur",
        description: 'Port militaire méditerranéen, base navale française',
        metaTitle: 'Tatoueurs à Toulon - Studios de tatouage Var',
        metaDescription:
          'Les tatoueurs toulonnais les plus créatifs. Trouvez votre studio de tatouage dans le Var.',
        seoKeywords: JSON.stringify(['tatoueur toulon', 'tattoo toulon', 'studio tatouage var']),
        isActive: true,
        isFeatured: false,
        priority: 30,
      },
    ]

    // Insert cities with proper error handling
    try {
      await City.createMany(cities)
      console.log(`Successfully seeded ${cities.length} cities`)
    } catch (error) {
      console.error('Error seeding cities:', error)
      throw error
    }
  }
}
