import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User, { UserRole } from '#models/user'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    // Check if users already exist to avoid duplicates
    const existingUsersCount = await User.query().count('* as total')
    if (Number(existingUsersCount[0].$extras.total) > 0) {
      console.log('Users already seeded, skipping...')
      return
    }

    const users = [
      // CLIENTS (10 users with role CLIENT = 1)
      {
        fullName: 'Sophie Martin',
        email: 'sophie.martin@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33612345678',
        bio: 'Passionnée de tatouages minimalistes',
        avatarUrl: 'https://i.pravatar.cc/300?img=1',
        birthDate: DateTime.fromISO('1992-05-15'),
        gender: 'female' as const,
        cityId: 1, // Paris
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 30 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 30 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 2 }),
      },
      {
        fullName: 'Thomas Dubois',
        email: 'thomas.dubois@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33623456789',
        bio: null,
        avatarUrl: 'https://i.pravatar.cc/300?img=12',
        birthDate: DateTime.fromISO('1988-11-22'),
        gender: 'male' as const,
        cityId: 2, // Lyon
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 15 }),
        phoneVerified: false,
        phoneVerifiedAt: null,
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 1 }),
      },
      {
        fullName: 'Julie Leroy',
        email: 'julie.leroy@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33634567890',
        bio: 'Adepte du style japonais',
        avatarUrl: 'https://i.pravatar.cc/300?img=5',
        birthDate: DateTime.fromISO('1995-03-08'),
        gender: 'female' as const,
        cityId: 3, // Marseille
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 20 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 18 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 5 }),
      },
      {
        fullName: 'Marc Rousseau',
        email: 'marc.rousseau@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33645678901',
        bio: null,
        avatarUrl: 'https://i.pravatar.cc/300?img=15',
        birthDate: DateTime.fromISO('1990-07-14'),
        gender: 'male' as const,
        cityId: 4, // Toulouse
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 45 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 45 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 3 }),
      },
      {
        fullName: 'Emma Moreau',
        email: 'emma.moreau@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33656789012',
        bio: 'Je cherche un tatouage tribal pour mon dos',
        avatarUrl: 'https://i.pravatar.cc/300?img=9',
        birthDate: DateTime.fromISO('1997-12-03'),
        gender: 'female' as const,
        cityId: 5, // Nice
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 10 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 8 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 12 }),
      },
      {
        fullName: 'Alexandre Petit',
        email: 'alex.petit@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33667890123',
        bio: null,
        avatarUrl: 'https://i.pravatar.cc/300?img=13',
        birthDate: DateTime.fromISO('1993-09-25'),
        gender: 'male' as const,
        cityId: 6, // Nantes
        emailVerified: false,
        emailVerifiedAt: null,
        phoneVerified: false,
        phoneVerifiedAt: null,
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 7 }),
      },
      {
        fullName: 'Camille Bernard',
        email: 'camille.bernard@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33678901234',
        bio: 'Fan de tatouages géométriques',
        avatarUrl: 'https://i.pravatar.cc/300?img=10',
        birthDate: DateTime.fromISO('1991-06-18'),
        gender: 'other' as const,
        cityId: 7, // Montpellier
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 25 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 20 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 8 }),
      },
      {
        fullName: 'Lucas Simon',
        email: 'lucas.simon@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33689012345',
        bio: null,
        avatarUrl: 'https://i.pravatar.cc/300?img=14',
        birthDate: DateTime.fromISO('1989-04-30'),
        gender: 'male' as const,
        cityId: 8, // Strasbourg
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 60 }),
        phoneVerified: false,
        phoneVerifiedAt: null,
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 14 }),
      },
      {
        fullName: 'Léa Durand',
        email: 'lea.durand@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33690123456',
        bio: 'Collectionneuse de tatouages floraux',
        avatarUrl: 'https://i.pravatar.cc/300?img=20',
        birthDate: DateTime.fromISO('1994-08-12'),
        gender: 'female' as const,
        cityId: 9, // Bordeaux
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 5 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 3 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 1 }),
      },
      {
        fullName: 'Hugo Laurent',
        email: 'hugo.laurent@example.com',
        password: 'password123',
        role: UserRole.CLIENT,
        phone: '+33601234567',
        bio: null,
        avatarUrl: 'https://i.pravatar.cc/300?img=18',
        birthDate: DateTime.fromISO('1996-02-27'),
        gender: 'male' as const,
        cityId: 10, // Lille
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 12 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 10 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 2 }),
      },

      // ARTISTS (20 users with role ARTIST = 2)
      {
        fullName: 'Vincent Noir',
        email: 'vincent.noir@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340001',
        bio: 'Artiste tatoueur spécialisé dans le réalisme depuis 15 ans',
        avatarUrl: 'https://i.pravatar.cc/300?img=33',
        birthDate: DateTime.fromISO('1985-03-15'),
        gender: 'male' as const,
        cityId: 1, // Paris
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 180 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 180 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 3 }),
      },
      {
        fullName: 'Sarah Ink',
        email: 'sarah.ink@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340002',
        bio: 'Passionnée par le dotwork et les mandalas',
        avatarUrl: 'https://i.pravatar.cc/300?img=28',
        birthDate: DateTime.fromISO('1990-07-22'),
        gender: 'female' as const,
        cityId: 1, // Paris
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 150 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 150 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 6 }),
      },
      {
        fullName: 'Maxime Shadow',
        email: 'maxime.shadow@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340003',
        bio: 'Expert en black & grey, portraits réalistes',
        avatarUrl: 'https://i.pravatar.cc/300?img=52',
        birthDate: DateTime.fromISO('1988-11-05'),
        gender: 'male' as const,
        cityId: 2, // Lyon
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 200 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 200 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 1 }),
      },
      {
        fullName: 'Amélie Colors',
        email: 'amelie.colors@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340004',
        bio: 'Spécialiste du watercolor et des compositions colorées',
        avatarUrl: 'https://i.pravatar.cc/300?img=47',
        birthDate: DateTime.fromISO('1992-05-18'),
        gender: 'female' as const,
        cityId: 2, // Lyon
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 90 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 90 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 4 }),
      },
      {
        fullName: 'Pierre Tribal',
        email: 'pierre.tribal@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340005',
        bio: 'Maître du style tribal polynésien traditionnel',
        avatarUrl: 'https://i.pravatar.cc/300?img=59',
        birthDate: DateTime.fromISO('1983-09-30'),
        gender: 'male' as const,
        cityId: 3, // Marseille
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 300 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 300 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 10 }),
      },
      {
        fullName: 'Clara Lines',
        email: 'clara.lines@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340006',
        bio: 'Artiste minimaliste, lignes fines et élégantes',
        avatarUrl: 'https://i.pravatar.cc/300?img=45',
        birthDate: DateTime.fromISO('1995-01-12'),
        gender: 'female' as const,
        cityId: 3, // Marseille
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 60 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 60 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 2 }),
      },
      {
        fullName: 'Julien Neo',
        email: 'julien.neo@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340007',
        bio: 'Spécialisé dans le neo-traditionnel européen',
        avatarUrl: 'https://i.pravatar.cc/300?img=56',
        birthDate: DateTime.fromISO('1987-06-25'),
        gender: 'male' as const,
        cityId: 4, // Toulouse
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 220 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 220 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 2 }),
      },
      {
        fullName: 'Manon Flowers',
        email: 'manon.flowers@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340008',
        bio: 'Compositions botaniques et illustrations délicates',
        avatarUrl: 'https://i.pravatar.cc/300?img=44',
        birthDate: DateTime.fromISO('1993-03-08'),
        gender: 'female' as const,
        cityId: 4, // Toulouse
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 100 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 100 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 5 }),
      },
      {
        fullName: 'Kevin Geometric',
        email: 'kevin.geometric@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340009',
        bio: 'Expert en géométrie sacrée et symétrie parfaite',
        avatarUrl: 'https://i.pravatar.cc/300?img=51',
        birthDate: DateTime.fromISO('1989-10-14'),
        gender: 'male' as const,
        cityId: 5, // Nice
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 250 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 250 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 8 }),
      },
      {
        fullName: 'Laura Japanese',
        email: 'laura.japanese@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340010',
        bio: 'Formée au Japon, spécialiste du Irezumi traditionnel',
        avatarUrl: 'https://i.pravatar.cc/300?img=32',
        birthDate: DateTime.fromISO('1991-08-19'),
        gender: 'female' as const,
        cityId: 5, // Nice
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 180 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 180 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 1 }),
      },
      {
        fullName: 'Antoine Biomech',
        email: 'antoine.biomech@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340011',
        bio: 'Créations biomécaniques et cyborg art',
        avatarUrl: 'https://i.pravatar.cc/300?img=60',
        birthDate: DateTime.fromISO('1986-12-07'),
        gender: 'male' as const,
        cityId: 6, // Nantes
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 270 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 270 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 3 }),
      },
      {
        fullName: 'Sophie Abstract',
        email: 'sophie.abstract@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340012',
        bio: 'Art abstrait et compositions expressionnistes',
        avatarUrl: 'https://i.pravatar.cc/300?img=27',
        birthDate: DateTime.fromISO('1994-04-21'),
        gender: 'female' as const,
        cityId: 6, // Nantes
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 70 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 70 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 7 }),
      },
      {
        fullName: 'Nicolas Traditional',
        email: 'nicolas.traditional@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340013',
        bio: 'Old school et American traditional depuis 20 ans',
        avatarUrl: 'https://i.pravatar.cc/300?img=68',
        birthDate: DateTime.fromISO('1982-02-28'),
        gender: 'male' as const,
        cityId: 7, // Montpellier
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 350 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 350 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 1 }),
      },
      {
        fullName: 'Isabelle Lettering',
        email: 'isabelle.lettering@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340014',
        bio: 'Calligraphie et lettering personnalisé',
        avatarUrl: 'https://i.pravatar.cc/300?img=26',
        birthDate: DateTime.fromISO('1990-11-16'),
        gender: 'female' as const,
        cityId: 7, // Montpellier
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 120 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 120 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 9 }),
      },
      {
        fullName: 'Fabien Portrait',
        email: 'fabien.portrait@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340015',
        bio: 'Portraits hyperréalistes et hommages personnalisés',
        avatarUrl: 'https://i.pravatar.cc/300?img=69',
        birthDate: DateTime.fromISO('1987-09-03'),
        gender: 'male' as const,
        cityId: 8, // Strasbourg
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 190 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 190 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 4 }),
      },
      {
        fullName: 'Chloé Ornamental',
        email: 'chloe.ornamental@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340016',
        bio: 'Ornements précieux et bijoux tatoués',
        avatarUrl: 'https://i.pravatar.cc/300?img=48',
        birthDate: DateTime.fromISO('1996-06-11'),
        gender: 'female' as const,
        cityId: 9, // Bordeaux
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 40 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 40 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 2 }),
      },
      {
        fullName: 'Romain Blackwork',
        email: 'romain.blackwork@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340017',
        bio: 'Blackwork intense et bold tribal moderne',
        avatarUrl: 'https://i.pravatar.cc/300?img=57',
        birthDate: DateTime.fromISO('1988-01-24'),
        gender: 'male' as const,
        cityId: 9, // Bordeaux
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 210 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 210 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 11 }),
      },
      {
        fullName: 'Audrey Celtic',
        email: 'audrey.celtic@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340018',
        bio: 'Spécialiste des motifs celtiques et nordiques',
        avatarUrl: 'https://i.pravatar.cc/300?img=43',
        birthDate: DateTime.fromISO('1992-07-09'),
        gender: 'female' as const,
        cityId: 10, // Lille
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 130 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 130 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 6 }),
      },
      {
        fullName: 'David Horror',
        email: 'david.horror@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340019',
        bio: 'Dark art, horror et macabre design',
        avatarUrl: 'https://i.pravatar.cc/300?img=70',
        birthDate: DateTime.fromISO('1984-10-31'),
        gender: 'male' as const,
        cityId: 11, // Rennes
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 320 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 320 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ days: 2 }),
      },
      {
        fullName: 'Marie Surrealism',
        email: 'marie.surrealism@tattoo.com',
        password: 'password123',
        role: UserRole.ARTIST,
        phone: '+33612340020',
        bio: 'Créations surréalistes et oniriques',
        avatarUrl: 'https://i.pravatar.cc/300?img=25',
        birthDate: DateTime.fromISO('1993-12-05'),
        gender: 'female' as const,
        cityId: 12, // Reims
        emailVerified: true,
        emailVerifiedAt: DateTime.now().minus({ days: 80 }),
        phoneVerified: true,
        phoneVerifiedAt: DateTime.now().minus({ days: 80 }),
        isActive: true,
        lastLoginAt: DateTime.now().minus({ hours: 3 }),
      },
    ]

    // Insert users with proper error handling
    try {
      await User.createMany(users)
      console.log(`Successfully seeded ${users.length} users (10 clients, 20 artists)`)
    } catch (error) {
      console.error('Error seeding users:', error)
      throw error
    }
  }
}
