import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import Salon, { SalonVerificationStatus } from '#models/salon'
import City from '#models/city'

export default class SalonSeeder extends BaseSeeder {
  async run() {
    // Check if salons already exist
    const existingSalonsCount = await Salon.query().count('* as total')
    if (Number(existingSalonsCount[0].$extras.total) > 0) {
      console.log('Salons already seeded, skipping...')
      return
    }

    // Get cities for salon locations
    const cities = await City.query().orderBy('priority', 'asc').limit(15)

    if (cities.length < 10) {
      console.log('❌ Salons need cities to be seeded first')
      return
    }

    const salonsData = [
      // Paris (3 salons)
      {
        name: 'Ink Palace Studio',
        description:
          "Studio de tatouage haut de gamme au cœur de Paris. Spécialisé dans le réalisme, le traditionnel et les créations personnalisées. Équipe d'artistes expérimentés depuis 2010.",
        shortDescription: 'Studio parisien spécialisé en réalisme et traditionnel',
        email: 'contact@inkpalace.fr',
        phone: '+33142365478',
        website: 'https://www.inkpalace.fr',
        cityId: cities[0].id,
        address: '15 rue de Rivoli',
        postalCode: '75001',
        latitude: 48.8566 + (Math.random() - 0.5) * 0.02,
        longitude: 2.3522 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Tatouage traditionnel', 'Réalisme', 'Noir et blanc', 'Couleur', 'Cover-up', 'Retouches'],
        priceRangeMin: 120,
        priceRangeMax: 400,
        instagramHandle: '@inkpalaceparis',
        galleryImages: [
          'https://picsum.photos/1200/800?random=1',
          'https://picsum.photos/1200/800?random=2',
          'https://picsum.photos/1200/800?random=3',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 60 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 1,
        averageRating: 4.8,
        totalReviews: 127,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Black Rose Tattoo',
        description:
          'Salon spécialisé dans les tatouages féminins, floraux et délicats. Atmosphère cosy et accueillante dans le Marais.',
        shortDescription: 'Tatouages féminins et floraux dans le Marais',
        email: 'hello@blackrosetattoo.fr',
        phone: '+33143298765',
        cityId: cities[0].id,
        address: '23 rue des Rosiers',
        postalCode: '75004',
        latitude: 48.8577 + (Math.random() - 0.5) * 0.02,
        longitude: 2.3596 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Tatouages féminins', 'Motifs floraux', 'Fine line', 'Minimaliste', 'Lettering'],
        priceRangeMin: 80,
        priceRangeMax: 250,
        instagramHandle: '@blackrosetattoo_paris',
        galleryImages: [
          'https://picsum.photos/1200/800?random=4',
          'https://picsum.photos/1200/800?random=5',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 45 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 2,
        averageRating: 4.9,
        totalReviews: 98,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Sacred Skin Paris',
        description:
          'Spécialistes du blackwork et des designs tribaux modernes. Équipe internationale avec plus de 30 ans d\'expérience cumulée.',
        shortDescription: 'Blackwork et tribal moderne',
        email: 'contact@sacredskinparis.fr',
        phone: '+33146578934',
        cityId: cities[0].id,
        address: '42 rue Oberkampf',
        postalCode: '75011',
        latitude: 48.8637 + (Math.random() - 0.5) * 0.02,
        longitude: 2.3797 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          tuesday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          wednesday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          thursday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          friday: { isOpen: true, openTime: '12:00', closeTime: '21:00' },
          saturday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          sunday: { isOpen: false },
        },
        services: ['Blackwork', 'Tribal', 'Dotwork', 'Ornements', 'Géométrique'],
        priceRangeMin: 150,
        priceRangeMax: 500,
        instagramHandle: '@sacredskinparis',
        galleryImages: [
          'https://picsum.photos/1200/800?random=6',
          'https://picsum.photos/1200/800?random=7',
          'https://picsum.photos/1200/800?random=8',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 90 }),
        isFeatured: false,
        priority: 10,
        averageRating: 4.7,
        totalReviews: 156,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },

      // Lyon (3 salons)
      {
        name: 'Lyon Ink Factory',
        description:
          'Studio moderne avec 6 artistes spécialisés. Du traditionnel au réalisme, nous couvrons tous les styles avec excellence.',
        shortDescription: 'Studio multi-styles au cœur de Lyon',
        email: 'studio@lyoninkfactory.fr',
        phone: '+33478123456',
        cityId: cities[1].id,
        address: '8 rue de la République',
        postalCode: '69002',
        latitude: 45.764 + (Math.random() - 0.5) * 0.02,
        longitude: 4.8357 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Réalisme', 'Traditionnel', 'Japonais', 'Portrait', 'Cover-up'],
        priceRangeMin: 100,
        priceRangeMax: 350,
        instagramHandle: '@lyoninkfactory',
        galleryImages: [
          'https://picsum.photos/1200/800?random=9',
          'https://picsum.photos/1200/800?random=10',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 30 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 3,
        averageRating: 4.6,
        totalReviews: 89,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },
      {
        name: 'Aquarelle Tattoo Lyon',
        description:
          'Spécialistes du watercolor et des créations colorées artistiques. Chaque pièce est une œuvre d\'art unique.',
        shortDescription: 'Watercolor et créations colorées',
        email: 'hello@aquarelletattoo.fr',
        phone: '+33478234567',
        cityId: cities[1].id,
        address: '15 rue Mercière',
        postalCode: '69002',
        latitude: 45.7640 + (Math.random() - 0.5) * 0.02,
        longitude: 4.8360 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Watercolor', 'Art abstrait', 'Illustrations colorées', 'Style painterly'],
        priceRangeMin: 120,
        priceRangeMax: 400,
        instagramHandle: '@aquarellelyon',
        galleryImages: [
          'https://picsum.photos/1200/800?random=11',
          'https://picsum.photos/1200/800?random=12',
          'https://picsum.photos/1200/800?random=13',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 75 }),
        isFeatured: false,
        priority: 12,
        averageRating: 4.8,
        totalReviews: 72,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Lyon Neo Traditional',
        description:
          'Équipe passionnée par le neo-traditionnel et les styles old school revisités. Ambiance rock et conviviale.',
        shortDescription: 'Neo-traditionnel et old school',
        email: 'info@lyonneotraditional.fr',
        phone: '+33478345678',
        cityId: cities[1].id,
        address: '22 cours Charlemagne',
        postalCode: '69002',
        latitude: 45.7435 + (Math.random() - 0.5) * 0.02,
        longitude: 4.8250 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Neo-traditionnel', 'Old school', 'American traditional', 'Pin-up', 'Flash'],
        priceRangeMin: 90,
        priceRangeMax: 300,
        instagramHandle: '@lyonneotraditional',
        galleryImages: ['https://picsum.photos/1200/800?random=14', 'https://picsum.photos/1200/800?random=15'],
        verificationStatus: SalonVerificationStatus.CONTACTED,
        isFeatured: false,
        priority: 15,
        averageRating: 4.5,
        totalReviews: 64,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Marseille (2 salons)
      {
        name: 'Mediterranean Ink',
        description:
          'Sur le Vieux-Port, studio alliant tradition et modernité. Spécialistes du réalisme marin et des créations personnalisées.',
        shortDescription: 'Réalisme marin et créations sur-mesure',
        email: 'contact@mediterraneanink.fr',
        phone: '+33491123456',
        cityId: cities[2].id,
        address: '12 quai du Port',
        postalCode: '13002',
        latitude: 43.2965 + (Math.random() - 0.5) * 0.02,
        longitude: 5.3698 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Réalisme', 'Thèmes marins', 'Portrait', 'Noir et blanc', 'Custom design'],
        priceRangeMin: 110,
        priceRangeMax: 380,
        instagramHandle: '@mediterraneanink',
        galleryImages: [
          'https://picsum.photos/1200/800?random=16',
          'https://picsum.photos/1200/800?random=17',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 50 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 4,
        averageRating: 4.7,
        totalReviews: 103,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Phocéenne Tattoo Art',
        description:
          'Collective d\'artistes marseillais proposant styles variés et ambiance méditerranéenne. Walk-ins bienvenus.',
        shortDescription: 'Collective multi-styles, walk-ins bienvenus',
        email: 'info@phoceennetattoo.fr',
        phone: '+33491234567',
        cityId: cities[2].id,
        address: '45 rue Paradis',
        postalCode: '13006',
        latitude: 43.2870 + (Math.random() - 0.5) * 0.02,
        longitude: 5.3810 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Traditionnel', 'Tribal', 'Lettering', 'Flash tattoos', 'Walk-ins'],
        priceRangeMin: 70,
        priceRangeMax: 250,
        instagramHandle: '@phoceennetattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=18'],
        verificationStatus: SalonVerificationStatus.CONTACTED,
        isFeatured: false,
        priority: 18,
        averageRating: 4.3,
        totalReviews: 57,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Toulouse (2 salons)
      {
        name: 'Pink City Tattoo',
        description:
          'Dans la ville rose, studio moderne spécialisé dans les créations colorées et les designs contemporains. Ambiance rock et conviviale.',
        shortDescription: 'Créations colorées et designs contemporains',
        email: 'info@pinkcitytattoo.fr',
        phone: '+33561234567',
        cityId: cities[3].id,
        address: '12 place du Capitole',
        postalCode: '31000',
        latitude: 43.6047 + (Math.random() - 0.5) * 0.02,
        longitude: 1.4442 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['New School coloré', 'Pop Art', 'Cartoon', 'Illustration', 'Typography moderne'],
        priceRangeMin: 85,
        priceRangeMax: 300,
        instagramHandle: '@pinkcitytattoo',
        galleryImages: [
          'https://picsum.photos/1200/800?random=19',
          'https://picsum.photos/1200/800?random=20',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 40 }),
        isFeatured: false,
        priority: 11,
        averageRating: 4.6,
        totalReviews: 67,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Toulouse Biomechanical Studio',
        description:
          'Spécialistes du biomécanique et du science-fiction. Pour les amateurs de designs futuristes et complexes.',
        shortDescription: 'Biomécanique et science-fiction',
        email: 'contact@toulousebiomech.fr',
        phone: '+33561345678',
        cityId: cities[3].id,
        address: '28 rue des Arts',
        postalCode: '31000',
        latitude: 43.6010 + (Math.random() - 0.5) * 0.02,
        longitude: 1.4470 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Biomécanique', 'Sci-fi', 'Cyborg', 'Alien', 'Futuriste'],
        priceRangeMin: 130,
        priceRangeMax: 450,
        instagramHandle: '@toulousebiomech',
        galleryImages: ['https://picsum.photos/1200/800?random=21'],
        verificationStatus: SalonVerificationStatus.ONBOARDING,
        isFeatured: false,
        priority: 16,
        averageRating: 4.7,
        totalReviews: 41,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },

      // Nice (2 salons)
      {
        name: 'Côte d\'Azur Tattoo',
        description:
          'Face à la Méditerranée, studio élégant proposant tatouages de luxe et designs exclusifs. Clientèle internationale.',
        shortDescription: 'Tatouages de luxe sur la Côte d\'Azur',
        email: 'contact@coteazurtattoo.fr',
        phone: '+33493123456',
        cityId: cities[4].id,
        address: '8 Promenade des Anglais',
        postalCode: '06000',
        latitude: 43.7102 + (Math.random() - 0.5) * 0.02,
        longitude: 7.2620 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Réalisme haut de gamme', 'Portrait', 'Design exclusif', 'Cover-up premium', 'Micro-réalisme'],
        priceRangeMin: 200,
        priceRangeMax: 600,
        instagramHandle: '@coteazurtattoo',
        galleryImages: [
          'https://picsum.photos/1200/800?random=22',
          'https://picsum.photos/1200/800?random=23',
          'https://picsum.photos/1200/800?random=24',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 20 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 5,
        averageRating: 4.9,
        totalReviews: 134,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Nice Minimalist Ink',
        description:
          'Studio spécialisé dans le minimalisme et les lignes fines. Designs épurés et élégants pour une clientèle raffinée.',
        shortDescription: 'Minimalisme et lignes fines',
        email: 'hello@niceminimalist.fr',
        phone: '+33493234567',
        cityId: cities[4].id,
        address: '15 rue Masséna',
        postalCode: '06000',
        latitude: 43.6960 + (Math.random() - 0.5) * 0.02,
        longitude: 7.2690 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Minimaliste', 'Fine line', 'Single needle', 'Micro tattoos', 'Geometric minimal'],
        priceRangeMin: 90,
        priceRangeMax: 280,
        instagramHandle: '@niceminimalist',
        galleryImages: ['https://picsum.photos/1200/800?random=25'],
        verificationStatus: SalonVerificationStatus.CONTACTED,
        isFeatured: false,
        priority: 14,
        averageRating: 4.8,
        totalReviews: 88,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },

      // Nantes (2 salons)
      {
        name: 'Nantes Ink Collective',
        description:
          'Collective de 5 artistes aux styles variés. Ambiance familiale et créative dans le centre historique.',
        shortDescription: 'Collective créatif multi-styles',
        email: 'contact@nantesink.fr',
        phone: '+33240123456',
        cityId: cities[5].id,
        address: '7 place Royale',
        postalCode: '44000',
        latitude: 47.2184 + (Math.random() - 0.5) * 0.02,
        longitude: -1.5536 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Réalisme', 'Japonais', 'Floral', 'Géométrique', 'Traditionnel'],
        priceRangeMin: 95,
        priceRangeMax: 320,
        instagramHandle: '@nantesink',
        galleryImages: ['https://picsum.photos/1200/800?random=26', 'https://picsum.photos/1200/800?random=27'],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 55 }),
        isFeatured: false,
        priority: 9,
        averageRating: 4.5,
        totalReviews: 76,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },
      {
        name: 'Breton Tattoo Heritage',
        description:
          'Spécialistes des motifs celtiques et bretons traditionnels. Préservation du patrimoine culturel dans l\'art corporel.',
        shortDescription: 'Motifs celtiques et bretons',
        email: 'contact@bretontattoo.fr',
        phone: '+33240234567',
        cityId: cities[5].id,
        address: '22 rue Crébillon',
        postalCode: '44000',
        latitude: 47.2120 + (Math.random() - 0.5) * 0.02,
        longitude: -1.5590 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Celtique', 'Breton', 'Nordique', 'Tribal traditionnel', 'Symboles anciens'],
        priceRangeMin: 100,
        priceRangeMax: 350,
        instagramHandle: '@bretontattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=28'],
        verificationStatus: SalonVerificationStatus.SCRAPED,
        isFeatured: false,
        priority: 20,
        averageRating: 4.4,
        totalReviews: 52,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },

      // Montpellier (2 salons)
      {
        name: 'Montpellier Artistic Tattoo',
        description:
          'Studio artistique proposant créations personnalisées et styles avant-gardistes. Pour les amoureux d\'art contemporain.',
        shortDescription: 'Art contemporain et créations personnalisées',
        email: 'art@montpelliertattoo.fr',
        phone: '+33467123456',
        cityId: cities[6].id,
        address: '5 place de la Comédie',
        postalCode: '34000',
        latitude: 43.6108 + (Math.random() - 0.5) * 0.02,
        longitude: 3.8767 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Art contemporain', 'Abstract', 'Surréalisme', 'Illustration unique', 'Design sur-mesure'],
        priceRangeMin: 110,
        priceRangeMax: 400,
        instagramHandle: '@montpellierartistictattoo',
        galleryImages: [
          'https://picsum.photos/1200/800?random=29',
          'https://picsum.photos/1200/800?random=30',
        ],
        verificationStatus: SalonVerificationStatus.CONTACTED,
        isFeatured: false,
        priority: 13,
        averageRating: 4.6,
        totalReviews: 63,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Southern Ink Montpellier',
        description:
          'Ambiance méditerranéenne et équipe jeune et dynamique. Tous styles, walk-ins acceptés.',
        shortDescription: 'Équipe jeune, tous styles, walk-ins OK',
        email: 'info@southernink.fr',
        phone: '+33467234567',
        cityId: cities[6].id,
        address: '18 rue de l\'Université',
        postalCode: '34000',
        latitude: 43.6085 + (Math.random() - 0.5) * 0.02,
        longitude: 3.8720 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          tuesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Traditionnel', 'Réalisme', 'Tribal', 'Lettering', 'Flash tattoos'],
        priceRangeMin: 75,
        priceRangeMax: 280,
        instagramHandle: '@southernink',
        galleryImages: ['https://picsum.photos/1200/800?random=31'],
        verificationStatus: SalonVerificationStatus.UNVERIFIED,
        isFeatured: false,
        priority: 22,
        averageRating: 4.2,
        totalReviews: 48,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Strasbourg (2 salons)
      {
        name: 'Strasbourg Ink Masters',
        description:
          'Studio franco-allemand alliant précision germanique et créativité française. Spécialistes du réalisme.',
        shortDescription: 'Réalisme de précision',
        email: 'contact@strasbourgink.fr',
        phone: '+33388123456',
        cityId: cities[7].id,
        address: '10 place Kléber',
        postalCode: '67000',
        latitude: 48.5734 + (Math.random() - 0.5) * 0.02,
        longitude: 7.7521 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Réalisme photographique', 'Portrait', 'Noir et blanc', 'Hyperréalisme', 'Cover-up'],
        priceRangeMin: 140,
        priceRangeMax: 450,
        instagramHandle: '@strasbourgink',
        galleryImages: ['https://picsum.photos/1200/800?random=32', 'https://picsum.photos/1200/800?random=33'],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 35 }),
        isFeatured: false,
        priority: 8,
        averageRating: 4.8,
        totalReviews: 91,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Alsace Traditional Tattoo',
        description:
          'Spécialistes du traditionnel alsacien et des motifs folkloriques régionaux. Patrimoine culturel préservé.',
        shortDescription: 'Traditionnel alsacien et folklorique',
        email: 'info@alsacetattoo.fr',
        phone: '+33388234567',
        cityId: cities[7].id,
        address: '25 rue du Vieux-Marché-aux-Poissons',
        postalCode: '67000',
        latitude: 48.5820 + (Math.random() - 0.5) * 0.02,
        longitude: 7.7485 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Folklorique alsacien', 'Traditionnel', 'Symboles régionaux', 'Germanic styles'],
        priceRangeMin: 90,
        priceRangeMax: 300,
        instagramHandle: '@alsacetattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=34'],
        verificationStatus: SalonVerificationStatus.SCRAPED,
        isFeatured: false,
        priority: 21,
        averageRating: 4.3,
        totalReviews: 39,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Bordeaux (2 salons)
      {
        name: 'Bordeaux Art & Ink',
        description:
          'Studio élégant dans le centre historique. Créations artistiques haut de gamme et ambiance raffinée.',
        shortDescription: 'Art haut de gamme dans le centre historique',
        email: 'contact@bordeauxartink.fr',
        phone: '+33556123456',
        cityId: cities[8].id,
        address: "8 cours de l'Intendance",
        postalCode: '33000',
        latitude: 44.8378 + (Math.random() - 0.5) * 0.02,
        longitude: -0.5792 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Art sur-mesure', 'Réalisme coloré', 'Aquarelle', 'Neo-traditional', 'Cover-up artistique'],
        priceRangeMin: 130,
        priceRangeMax: 420,
        instagramHandle: '@bordeauxartink',
        galleryImages: [
          'https://picsum.photos/1200/800?random=35',
          'https://picsum.photos/1200/800?random=36',
        ],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 25 }),
        verifiedBy: 'admin@blottr.fr',
        isFeatured: true,
        priority: 6,
        averageRating: 4.7,
        totalReviews: 108,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Bassins à Flot Tattoo',
        description:
          'Dans le nouveau quartier branché, studio moderne aux styles variés. Ambiance jeune et créative.',
        shortDescription: 'Studio moderne, styles variés',
        email: 'hello@bassinsaflottattoo.fr',
        phone: '+33556234567',
        cityId: cities[8].id,
        address: '15 rue Achard',
        postalCode: '33300',
        latitude: 44.8620 + (Math.random() - 0.5) * 0.02,
        longitude: -0.5560 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Traditionnel', 'Réalisme', 'Dotwork', 'Géométrique', 'Illustration'],
        priceRangeMin: 85,
        priceRangeMax: 310,
        instagramHandle: '@bassinsaflottattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=37'],
        verificationStatus: SalonVerificationStatus.ONBOARDING,
        isFeatured: false,
        priority: 17,
        averageRating: 4.5,
        totalReviews: 54,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Lille (2 salons)
      {
        name: 'Northern Ink Lille',
        description:
          'Studio du Nord spécialisé en blackwork et dark art. Ambiance underground et créations audacieuses.',
        shortDescription: 'Blackwork et dark art',
        email: 'contact@northernink.fr',
        phone: '+33320123456',
        cityId: cities[9].id,
        address: '12 rue de Béthune',
        postalCode: '59000',
        latitude: 50.6292 + (Math.random() - 0.5) * 0.02,
        longitude: 3.0573 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '12:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '12:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Blackwork', 'Dark art', 'Horror', 'Dotwork noir', 'Tribal moderne'],
        priceRangeMin: 100,
        priceRangeMax: 380,
        instagramHandle: '@northerninklille',
        galleryImages: ['https://picsum.photos/1200/800?random=38', 'https://picsum.photos/1200/800?random=39'],
        verificationStatus: SalonVerificationStatus.CONTACTED,
        isFeatured: false,
        priority: 19,
        averageRating: 4.6,
        totalReviews: 71,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },
      {
        name: 'Lille Colorful Creations',
        description:
          'Spécialistes du tatouage coloré et joyeux. Parfait pour les designs lumineux et positifs.',
        shortDescription: 'Tatouages colorés et joyeux',
        email: 'hello@lillecolorful.fr',
        phone: '+33320234567',
        cityId: cities[9].id,
        address: '8 place de la République',
        postalCode: '59000',
        latitude: 50.6310 + (Math.random() - 0.5) * 0.02,
        longitude: 3.0545 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Watercolor', 'Designs colorés', 'Floral', 'Illustration pop', 'Art joyeux'],
        priceRangeMin: 80,
        priceRangeMax: 270,
        instagramHandle: '@lillecolorful',
        galleryImages: ['https://picsum.photos/1200/800?random=40'],
        verificationStatus: SalonVerificationStatus.SCRAPED,
        isFeatured: false,
        priority: 23,
        averageRating: 4.4,
        totalReviews: 59,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Rennes (1 salon)
      {
        name: 'Rennes Celtic Tattoo',
        description:
          'Spécialistes des motifs celtiques bretons et de l\'art nordique. Tradition et modernité.',
        shortDescription: 'Celtique breton et nordique',
        email: 'contact@rennesceltictattoo.fr',
        phone: '+33299123456',
        cityId: cities[10].id,
        address: '5 place des Lices',
        postalCode: '35000',
        latitude: 48.1173 + (Math.random() - 0.5) * 0.02,
        longitude: -1.6778 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Celtique', 'Nordique', 'Viking', 'Tribal breton', 'Symboles anciens'],
        priceRangeMin: 95,
        priceRangeMax: 330,
        instagramHandle: '@rennesceltictattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=41'],
        verificationStatus: SalonVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 65 }),
        isFeatured: false,
        priority: 7,
        averageRating: 4.7,
        totalReviews: 82,
        acceptsWalkIns: false,
        appointmentRequired: true,
      },

      // Reims (1 salon)
      {
        name: 'Champagne Ink Reims',
        description:
          'Studio champenois proposant styles variés et ambiance conviviale. Walk-ins et rendez-vous.',
        shortDescription: 'Styles variés, ambiance conviviale',
        email: 'info@champagneink.fr',
        phone: '+33326123456',
        cityId: cities[11].id,
        address: '10 place Drouet-d\'Erlon',
        postalCode: '51100',
        latitude: 49.2583 + (Math.random() - 0.5) * 0.02,
        longitude: 4.0317 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          wednesday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          thursday: { isOpen: true, openTime: '11:00', closeTime: '19:00' },
          friday: { isOpen: true, openTime: '11:00', closeTime: '20:00' },
          saturday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          sunday: { isOpen: false },
        },
        services: ['Traditionnel', 'Réalisme', 'Lettering', 'Flash tattoos', 'Cover-up'],
        priceRangeMin: 85,
        priceRangeMax: 290,
        instagramHandle: '@champagneink',
        galleryImages: ['https://picsum.photos/1200/800?random=42'],
        verificationStatus: SalonVerificationStatus.UNVERIFIED,
        isFeatured: false,
        priority: 24,
        averageRating: 4.3,
        totalReviews: 46,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },

      // Le Havre (1 salon)
      {
        name: 'Le Havre Port Tattoo',
        description:
          'Face à la mer, studio spécialisé en thèmes marins et réalisme. Atmosphère portuaire authentique.',
        shortDescription: 'Thèmes marins et réalisme',
        email: 'contact@lehavretattoo.fr',
        phone: '+33235123456',
        cityId: cities[12].id,
        address: '12 quai Southampton',
        postalCode: '76600',
        latitude: 49.4944 + (Math.random() - 0.5) * 0.02,
        longitude: 0.1079 + (Math.random() - 0.5) * 0.02,
        openingHours: {
          monday: { isOpen: false },
          tuesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          wednesday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          thursday: { isOpen: true, openTime: '10:00', closeTime: '18:00' },
          friday: { isOpen: true, openTime: '10:00', closeTime: '19:00' },
          saturday: { isOpen: true, openTime: '09:00', closeTime: '17:00' },
          sunday: { isOpen: false },
        },
        services: ['Thèmes marins', 'Réalisme', 'Traditionnel marin', 'Ancres et navires', 'Portrait'],
        priceRangeMin: 90,
        priceRangeMax: 310,
        instagramHandle: '@lehavretattoo',
        galleryImages: ['https://picsum.photos/1200/800?random=43'],
        verificationStatus: SalonVerificationStatus.SCRAPED,
        isFeatured: false,
        priority: 25,
        averageRating: 4.2,
        totalReviews: 37,
        acceptsWalkIns: true,
        appointmentRequired: false,
      },
    ]

    // Insert salons with proper error handling
    try {
      const createdSalons = []
      for (let i = 0; i < salonsData.length; i++) {
        const salonData = salonsData[i]
        try {
          console.log(`Creating salon ${i + 1}/${salonsData.length}: ${salonData.name}`)
          const salon = await Salon.create(salonData)
          createdSalons.push(salon)
        } catch (error) {
          console.error(`\n❌ Error creating salon "${salonData.name}" (index ${i}):`)
          console.error('Salon data:', JSON.stringify(salonData, null, 2))
          console.error('Error:', error)
          throw error
        }
      }
      console.log(`✅ Successfully seeded ${createdSalons.length} salons`)
    } catch (error) {
      console.error('\n🚨 Fatal error seeding salons:', error)
      throw error
    }
  }
}
