import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import Artist, { ArtistVerificationStatus, ArtistExperienceLevel } from '#models/artist'
import User, { UserRole } from '#models/user'

export default class ArtistSeeder extends BaseSeeder {
  async run() {
    // Check if artists already exist
    const existingArtistsCount = await Artist.query().count('* as total')
    if (Number(existingArtistsCount[0].$extras.total) > 0) {
      console.log('Artists already seeded, skipping...')
      return
    }

    // Get all users with ARTIST role (should be 20 from user_seeder)
    const artistUsers = await User.query().where('role', UserRole.ARTIST).orderBy('id', 'asc')

    if (artistUsers.length < 20) {
      console.log(`❌ Artists need 20 artist users, found ${artistUsers.length}`)
      return
    }

    const artistsData = [
      // Artist 1 - Vincent Noir (Réalisme expert)
      {
        userId: artistUsers[0].id,
        stageName: 'Vincent Noir',
        bio: 'Artiste tatoueur spécialisé dans le réalisme depuis 15 ans. Formé auprès des plus grands maîtres européens, je transforme vos idées en œuvres d\'art permanentes.',
        shortBio: 'Expert réalisme 15 ans',
        specialty: 'Réalisme photographique et portraits',
        yearsExperience: 15,
        startedTattooingAt: DateTime.now().minus({ years: 15 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['realistic', 'black_and_grey', 'portrait', 'hyperrealism'],
        cityId: artistUsers[0].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 200,
        maxPrice: 600,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=201',
          'https://picsum.photos/800/600?random=202',
          'https://picsum.photos/800/600?random=203',
          'https://picsum.photos/800/600?random=204',
        ],
        instagramHandle: '@vincent.noir.tattoo',
        website: 'https://vincentnoir.art',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 90 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: true,
        priority: 1,
        averageRating: 4.9,
        totalReviews: 145,
        totalTattoos: 234,
        profileViews: 5621,
      },

      // Artist 2 - Sarah Ink (Dotwork)
      {
        userId: artistUsers[1].id,
        stageName: 'Sarah Ink',
        bio: 'Passionnée par le dotwork et les mandalas. Chaque création est une méditation artistique, une fusion entre géométrie sacrée et expression personnelle.',
        shortBio: 'Dotwork & géométrie sacrée',
        specialty: 'Dotwork, mandalas et ornements',
        yearsExperience: 8,
        startedTattooingAt: DateTime.now().minus({ years: 8 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['dotwork', 'geometric', 'mandala', 'ornamental'],
        cityId: artistUsers[1].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 150,
        maxPrice: 450,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=205',
          'https://picsum.photos/800/600?random=206',
          'https://picsum.photos/800/600?random=207',
        ],
        instagramHandle: '@sarah.ink.mandala',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 60 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: true,
        priority: 2,
        averageRating: 4.8,
        totalReviews: 98,
        totalTattoos: 156,
        profileViews: 4321,
      },

      // Artist 3 - Maxime Shadow (Black & Grey)
      {
        userId: artistUsers[2].id,
        stageName: 'Maxime Shadow',
        bio: 'Expert en black & grey et portraits réalistes. Mon objectif: capturer l\'âme dans chaque tatouage avec des contrastes saisissants.',
        shortBio: 'Black & grey expert',
        specialty: 'Portraits et black & grey',
        yearsExperience: 12,
        startedTattooingAt: DateTime.now().minus({ years: 12 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['black_and_grey', 'realistic', 'portrait', 'realism'],
        cityId: artistUsers[2].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 180,
        maxPrice: 550,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=208',
          'https://picsum.photos/800/600?random=209',
          'https://picsum.photos/800/600?random=210',
        ],
        instagramHandle: '@maxime.shadow',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 120 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: true,
        priority: 3,
        averageRating: 4.9,
        totalReviews: 132,
        totalTattoos: 289,
        profileViews: 6789,
      },

      // Artist 4 - Amélie Colors (Watercolor)
      {
        userId: artistUsers[3].id,
        stageName: 'Amélie Colors',
        bio: 'Spécialiste du watercolor et des compositions colorées. L\'art abstrait rencontre la peau pour créer des œuvres uniques et vibrantes.',
        shortBio: 'Watercolor specialist',
        specialty: 'Aquarelle et compositions colorées',
        yearsExperience: 6,
        startedTattooingAt: DateTime.now().minus({ years: 6 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['watercolor', 'abstract', 'colorful', 'painterly'],
        cityId: artistUsers[3].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 140,
        maxPrice: 420,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=211',
          'https://picsum.photos/800/600?random=212',
        ],
        instagramHandle: '@amelie.colors.art',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 45 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 8,
        averageRating: 4.7,
        totalReviews: 76,
        totalTattoos: 123,
        profileViews: 3456,
      },

      // Artist 5 - Pierre Tribal (Polynesian)
      {
        userId: artistUsers[4].id,
        stageName: 'Pierre Tribal',
        bio: 'Maître du style tribal polynésien traditionnel. 20 ans d\'expérience avec formation en Polynésie. Respect des traditions et symboles ancestraux.',
        shortBio: 'Tribal polynésien maître',
        specialty: 'Tribal polynésien traditionnel',
        yearsExperience: 20,
        startedTattooingAt: DateTime.now().minus({ years: 20 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['tribal', 'polynesian', 'maori', 'pacific'],
        cityId: artistUsers[4].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 160,
        maxPrice: 480,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=213',
          'https://picsum.photos/800/600?random=214',
          'https://picsum.photos/800/600?random=215',
        ],
        instagramHandle: '@pierre.tribal.poly',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 180 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: true,
        priority: 4,
        averageRating: 4.8,
        totalReviews: 167,
        totalTattoos: 412,
        profileViews: 8934,
      },

      // Artist 6 - Clara Lines (Minimalist)
      {
        userId: artistUsers[5].id,
        stageName: 'Clara Lines',
        bio: 'Artiste minimaliste, lignes fines et élégantes. Philosophie : moins c\'est plus. Créations épurées et intemporelles.',
        shortBio: 'Minimaliste fine line',
        specialty: 'Minimalisme et lignes fines',
        yearsExperience: 5,
        startedTattooingAt: DateTime.now().minus({ years: 5 }),
        experienceLevel: ArtistExperienceLevel.INTERMEDIATE,
        artStyles: ['minimalist', 'fine_line', 'single_needle', 'delicate'],
        cityId: artistUsers[5].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 90,
        maxPrice: 280,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=216',
          'https://picsum.photos/800/600?random=217',
        ],
        instagramHandle: '@clara.lines.minimal',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 30 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 10,
        averageRating: 4.9,
        totalReviews: 89,
        totalTattoos: 145,
        profileViews: 5234,
      },

      // Artist 7 - Julien Neo (Neo-traditional)
      {
        userId: artistUsers[6].id,
        stageName: 'Julien Neo',
        bio: 'Spécialisé dans le neo-traditionnel européen. Couleurs vibrantes, lignes audacieuses et compositions dynamiques.',
        shortBio: 'Neo-traditionnel européen',
        specialty: 'Neo-traditionnel',
        yearsExperience: 10,
        startedTattooingAt: DateTime.now().minus({ years: 10 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['neo_traditional', 'traditional', 'colorful', 'bold'],
        cityId: artistUsers[6].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 120,
        maxPrice: 380,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=218',
          'https://picsum.photos/800/600?random=219',
        ],
        instagramHandle: '@julien.neo.trad',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 75 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 7,
        averageRating: 4.6,
        totalReviews: 93,
        totalTattoos: 178,
        profileViews: 4123,
      },

      // Artist 8 - Manon Flowers (Botanical)
      {
        userId: artistUsers[7].id,
        stageName: 'Manon Flowers',
        bio: 'Compositions botaniques et illustrations délicates. La nature comme source d\'inspiration infinie pour des créations poétiques.',
        shortBio: 'Botanique et floral',
        specialty: 'Illustrations botaniques',
        yearsExperience: 7,
        startedTattooingAt: DateTime.now().minus({ years: 7 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['floral', 'botanical', 'illustrative', 'nature'],
        cityId: artistUsers[7].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 110,
        maxPrice: 350,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=220',
          'https://picsum.photos/800/600?random=221',
        ],
        instagramHandle: '@manon.flowers.ink',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 50 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: false,
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 12,
        averageRating: 4.7,
        totalReviews: 71,
        totalTattoos: 134,
        profileViews: 3789,
      },

      // Artist 9 - Kevin Geometric (Sacred Geometry)
      {
        userId: artistUsers[8].id,
        stageName: 'Kevin Geometric',
        bio: 'Expert en géométrie sacrée et symétrie parfaite. Précision mathématique rencontre beauté esthétique.',
        shortBio: 'Géométrie sacrée expert',
        specialty: 'Géométrie sacrée',
        yearsExperience: 9,
        startedTattooingAt: DateTime.now().minus({ years: 9 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['geometric', 'sacred_geometry', 'symmetry', 'mathematical'],
        cityId: artistUsers[8].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 130,
        maxPrice: 400,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=222',
          'https://picsum.photos/800/600?random=223',
        ],
        instagramHandle: '@kevin.geometric',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 100 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 9,
        averageRating: 4.8,
        totalReviews: 104,
        totalTattoos: 187,
        profileViews: 4567,
      },

      // Artist 10 - Laura Japanese (Irezumi)
      {
        userId: artistUsers[9].id,
        stageName: 'Laura Japanese',
        bio: 'Formée au Japon, spécialiste du Irezumi traditionnel. Respect profond de la tradition et des symboles japonais.',
        shortBio: 'Irezumi traditionnel',
        specialty: 'Tatouage japonais traditionnel',
        yearsExperience: 11,
        startedTattooingAt: DateTime.now().minus({ years: 11 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['japanese', 'irezumi', 'traditional_japanese', 'oriental'],
        cityId: artistUsers[9].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 170,
        maxPrice: 520,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=224',
          'https://picsum.photos/800/600?random=225',
          'https://picsum.photos/800/600?random=226',
        ],
        instagramHandle: '@laura.japanese.ink',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 140 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: true,
        priority: 5,
        averageRating: 4.9,
        totalReviews: 156,
        totalTattoos: 267,
        profileViews: 7234,
      },

      // Artist 11 - Antoine Biomech (Biomechanical)
      {
        userId: artistUsers[10].id,
        stageName: 'Antoine Biomech',
        bio: 'Créations biomécaniques et cyborg art. Le futur rencontre le présent dans des designs complexes et fascinants.',
        shortBio: 'Biomécanique & sci-fi',
        specialty: 'Biomécanique',
        yearsExperience: 13,
        startedTattooingAt: DateTime.now().minus({ years: 13 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['biomechanical', 'scifi', 'cyborg', 'futuristic'],
        cityId: artistUsers[10].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 160,
        maxPrice: 500,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=227',
          'https://picsum.photos/800/600?random=228',
        ],
        instagramHandle: '@antoine.biomech',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 110 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 6,
        averageRating: 4.7,
        totalReviews: 118,
        totalTattoos: 201,
        profileViews: 5678,
      },

      // Artist 12 - Sophie Abstract (Abstract Art)
      {
        userId: artistUsers[11].id,
        stageName: 'Sophie Abstract',
        bio: 'Art abstrait et compositions expressionnistes. Libérez votre créativité avec des œuvres uniques et personnelles.',
        shortBio: 'Art abstrait expressionniste',
        specialty: 'Art abstrait',
        yearsExperience: 6,
        startedTattooingAt: DateTime.now().minus({ years: 6 }),
        experienceLevel: ArtistExperienceLevel.INTERMEDIATE,
        artStyles: ['abstract', 'expressionist', 'artistic', 'contemporary'],
        cityId: artistUsers[11].cityId!,
        acceptsBookings: true,
        appointmentOnly: false,
        minPrice: 100,
        maxPrice: 320,
        currency: 'EUR',
        portfolioImages: ['https://picsum.photos/800/600?random=229'],
        instagramHandle: '@sophie.abstract.art',
        verificationStatus: ArtistVerificationStatus.CONTACTED,
        hasHealthCertificate: true,
        hasProfessionalInsurance: false,
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 15,
        averageRating: 4.5,
        totalReviews: 62,
        totalTattoos: 98,
        profileViews: 2345,
      },

      // Artist 13 - Nicolas Traditional (American Traditional)
      {
        userId: artistUsers[12].id,
        stageName: 'Nicolas Traditional',
        bio: 'Old school et American traditional depuis 20 ans. Les classiques ne meurent jamais - audace, couleurs vives et lignes franches.',
        shortBio: 'American traditional 20 ans',
        specialty: 'American traditional',
        yearsExperience: 20,
        startedTattooingAt: DateTime.now().minus({ years: 20 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['traditional', 'old_school', 'american_traditional', 'classic'],
        cityId: artistUsers[12].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 140,
        maxPrice: 380,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=230',
          'https://picsum.photos/800/600?random=231',
        ],
        instagramHandle: '@nicolas.traditional',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 200 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 11,
        averageRating: 4.8,
        totalReviews: 189,
        totalTattoos: 456,
        profileViews: 9123,
      },

      // Artist 14 - Isabelle Lettering (Calligraphy)
      {
        userId: artistUsers[13].id,
        stageName: 'Isabelle Lettering',
        bio: 'Calligraphie et lettering personnalisé. Vos mots deviennent art avec style et élégance.',
        shortBio: 'Calligraphie & lettering',
        specialty: 'Lettering et calligraphie',
        yearsExperience: 8,
        startedTattooingAt: DateTime.now().minus({ years: 8 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['lettering', 'calligraphy', 'script', 'typography'],
        cityId: artistUsers[13].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 80,
        maxPrice: 250,
        currency: 'EUR',
        portfolioImages: ['https://picsum.photos/800/600?random=232'],
        instagramHandle: '@isabelle.lettering',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 65 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 14,
        averageRating: 4.6,
        totalReviews: 84,
        totalTattoos: 167,
        profileViews: 3890,
      },

      // Artist 15 - Fabien Portrait (Hyperrealism)
      {
        userId: artistUsers[14].id,
        stageName: 'Fabien Portrait',
        bio: 'Portraits hyperréalistes et hommages personnalisés. Immortalisez vos proches avec une précision photographique.',
        shortBio: 'Portraits hyperréalistes',
        specialty: 'Portraits réalistes',
        yearsExperience: 14,
        startedTattooingAt: DateTime.now().minus({ years: 14 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['portrait', 'realistic', 'hyperrealism', 'memorial'],
        cityId: artistUsers[14].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 190,
        maxPrice: 580,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=233',
          'https://picsum.photos/800/600?random=234',
        ],
        instagramHandle: '@fabien.portrait',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 85 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: true,
        isAcceptingNewClients: false,
        priority: 3,
        averageRating: 4.9,
        totalReviews: 201,
        totalTattoos: 312,
        profileViews: 11234,
      },

      // Artist 16 - Chloé Ornamental (Jewelry)
      {
        userId: artistUsers[15].id,
        stageName: 'Chloé Ornamental',
        bio: 'Ornements précieux et bijoux tatoués. Élégance et raffinement pour des créations délicates et sophistiquées.',
        shortBio: 'Ornements & bijoux',
        specialty: 'Ornements et bijoux',
        yearsExperience: 5,
        startedTattooingAt: DateTime.now().minus({ years: 5 }),
        experienceLevel: ArtistExperienceLevel.INTERMEDIATE,
        artStyles: ['ornamental', 'jewelry', 'elegant', 'decorative'],
        cityId: artistUsers[15].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 110,
        maxPrice: 340,
        currency: 'EUR',
        portfolioImages: ['https://picsum.photos/800/600?random=235'],
        instagramHandle: '@chloe.ornamental',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 25 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 13,
        averageRating: 4.8,
        totalReviews: 73,
        totalTattoos: 119,
        profileViews: 4012,
      },

      // Artist 17 - Romain Blackwork (Bold Blackwork)
      {
        userId: artistUsers[16].id,
        stageName: 'Romain Blackwork',
        bio: 'Blackwork intense et bold tribal moderne. Pour ceux qui osent le noir absolu et les designs audacieux.',
        shortBio: 'Blackwork bold intense',
        specialty: 'Blackwork et tribal moderne',
        yearsExperience: 10,
        startedTattooingAt: DateTime.now().minus({ years: 10 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['blackwork', 'tribal_modern', 'bold', 'dark'],
        cityId: artistUsers[16].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 150,
        maxPrice: 460,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=236',
          'https://picsum.photos/800/600?random=237',
        ],
        instagramHandle: '@romain.blackwork',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 95 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 8,
        averageRating: 4.7,
        totalReviews: 112,
        totalTattoos: 198,
        profileViews: 5432,
      },

      // Artist 18 - Audrey Celtic (Celtic & Nordic)
      {
        userId: artistUsers[17].id,
        stageName: 'Audrey Celtic',
        bio: 'Spécialiste des motifs celtiques et nordiques. Connexion avec nos racines ancestrales à travers l\'art corporel.',
        shortBio: 'Celtique & nordique',
        specialty: 'Motifs celtiques',
        yearsExperience: 7,
        startedTattooingAt: DateTime.now().minus({ years: 7 }),
        experienceLevel: ArtistExperienceLevel.ADVANCED,
        artStyles: ['celtic', 'nordic', 'viking', 'ancient'],
        cityId: artistUsers[17].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 100,
        maxPrice: 330,
        currency: 'EUR',
        portfolioImages: ['https://picsum.photos/800/600?random=238'],
        instagramHandle: '@audrey.celtic',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 70 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: false,
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 16,
        averageRating: 4.6,
        totalReviews: 67,
        totalTattoos: 134,
        profileViews: 3234,
      },

      // Artist 19 - David Horror (Dark Art)
      {
        userId: artistUsers[18].id,
        stageName: 'David Horror',
        bio: 'Dark art, horror et macabre design. L\'obscurité a sa propre beauté troublante et fascinante.',
        shortBio: 'Dark art & horror',
        specialty: 'Horror et dark art',
        yearsExperience: 16,
        startedTattooingAt: DateTime.now().minus({ years: 16 }),
        experienceLevel: ArtistExperienceLevel.EXPERT,
        artStyles: ['horror', 'dark_art', 'macabre', 'gothic'],
        cityId: artistUsers[18].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 140,
        maxPrice: 440,
        currency: 'EUR',
        portfolioImages: [
          'https://picsum.photos/800/600?random=239',
          'https://picsum.photos/800/600?random=240',
        ],
        instagramHandle: '@david.horror.art',
        verificationStatus: ArtistVerificationStatus.VERIFIED,
        verifiedAt: DateTime.now().minus({ days: 150 }),
        verifiedBy: 'admin@blottr.fr',
        hasHealthCertificate: true,
        hasProfessionalInsurance: true,
        healthCertificateExpiresAt: DateTime.now().plus({ years: 1 }),
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 9,
        averageRating: 4.8,
        totalReviews: 143,
        totalTattoos: 278,
        profileViews: 6789,
      },

      // Artist 20 - Marie Surrealism (Surrealist)
      {
        userId: artistUsers[19].id,
        stageName: 'Marie Surrealism',
        bio: 'Créations surréalistes et oniriques. Vos rêves les plus fous deviennent réalité sur votre peau.',
        shortBio: 'Surréalisme onirique',
        specialty: 'Art surréaliste',
        yearsExperience: 6,
        startedTattooingAt: DateTime.now().minus({ years: 6 }),
        experienceLevel: ArtistExperienceLevel.INTERMEDIATE,
        artStyles: ['surrealism', 'dreamy', 'artistic', 'imaginative'],
        cityId: artistUsers[19].cityId!,
        acceptsBookings: true,
        appointmentOnly: true,
        minPrice: 120,
        maxPrice: 370,
        currency: 'EUR',
        portfolioImages: ['https://picsum.photos/800/600?random=241'],
        instagramHandle: '@marie.surrealism',
        verificationStatus: ArtistVerificationStatus.CONTACTED,
        hasHealthCertificate: true,
        hasProfessionalInsurance: false,
        isActive: true,
        isFeatured: false,
        isAcceptingNewClients: true,
        priority: 17,
        averageRating: 4.5,
        totalReviews: 58,
        totalTattoos: 102,
        profileViews: 2890,
      },
    ]

    // Insert artists with proper error handling
    try {
      await Artist.createMany(artistsData)
      console.log(`Successfully seeded ${artistsData.length} artists`)
    } catch (error) {
      console.error('Error seeding artists:', error)
      throw error
    }
  }
}
