import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import Tattoo from '#models/tattoo'
import Artist from '#models/artist'
import Tag from '#models/tag'
import { TattooStatus, TattooStyle, BodyPlacement, SizeCategory, ColorType } from '#models/tattoo'

export default class extends BaseSeeder {
  async run() {
    // Get all artists to associate with tattoos
    const artists = await Artist.query()
    if (artists.length === 0) {
      console.log('No artists found. Please run artist seeder first.')
      return
    }

    // Get some tags for association
    const styleTags = await Tag.query().where('category', 'style')
    const subjectTags = await Tag.query().where('category', 'subject')
    const bodyPartTags = await Tag.query().where('category', 'body_part')

    const sampleTattoos = [
      {
        artistId: artists[0].id,
        title: 'Dragon Sleeve Traditional',
        description: 'Full sleeve traditional dragon tattoo with vibrant colors and bold lines',
        slug: 'dragon-sleeve-traditional-001',
        originalFilename: 'dragon_sleeve_001.jpg',
        storagePath: '/uploads/tattoos/2024/01/dragon_sleeve_001.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/01/dragon_sleeve_001_thumb.jpg',
          medium: '/uploads/tattoos/2024/01/dragon_sleeve_001_medium.jpg',
          large: '/uploads/tattoos/2024/01/dragon_sleeve_001_large.jpg',
          original: '/uploads/tattoos/2024/01/dragon_sleeve_001.jpg',
        },
        primaryColor: '#FF6B35',
        fileSize: 2456789,
        dimensions: {
          width: 1920,
          height: 2880,
          aspectRatio: 0.67,
        },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.TRADITIONAL,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 4,
        estimatedHours: 12.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1250,
        likeCount: 89,
        shareCount: 23,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1800.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage dragon traditionnel sur bras complet avec couleurs vives',
          en: 'Traditional dragon tattoo full arm sleeve with vibrant colors',
        },
        searchKeywords: ['dragon', 'traditional', 'sleeve', 'arm', 'colorful'],
        metaTitle: 'Dragon Sleeve Traditional Tattoo | Blottr Portfolio',
        metaDescription:
          'Stunning traditional dragon sleeve tattoo featuring vibrant colors and expert linework',
        publishedAt: DateTime.fromISO('2024-01-15T10:00:00Z'),
      },
      {
        artistId: artists[1].id,
        title: 'Realistic Rose Portrait',
        description: 'Photorealistic black and grey rose with intricate details and shading',
        slug: 'realistic-rose-portrait-002',
        originalFilename: 'realistic_rose_002.jpg',
        storagePath: '/uploads/tattoos/2024/01/realistic_rose_002.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/01/realistic_rose_002_thumb.jpg',
          medium: '/uploads/tattoos/2024/01/realistic_rose_002_medium.jpg',
          large: '/uploads/tattoos/2024/01/realistic_rose_002_large.jpg',
          original: '/uploads/tattoos/2024/01/realistic_rose_002.jpg',
        },
        primaryColor: '#666666',
        fileSize: 1845623,
        dimensions: {
          width: 1440,
          height: 1920,
          aspectRatio: 0.75,
        },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.SHOULDER,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 2,
        estimatedHours: 6.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 892,
        likeCount: 67,
        shareCount: 12,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 650.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage rose réaliste en noir et gris sur épaule',
          en: 'Realistic black and grey rose tattoo on shoulder',
        },
        searchKeywords: ['rose', 'realistic', 'black and grey', 'shoulder', 'flower'],
        metaTitle: 'Realistic Rose Tattoo | Professional Portfolio',
        metaDescription:
          'Beautiful realistic rose tattoo in black and grey with stunning detail work',
        publishedAt: DateTime.fromISO('2024-01-25T16:45:00Z'),
      },
      {
        artistId: artists[2].id,
        title: 'Minimalist Geometric Triangle',
        description: 'Clean geometric triangle design with fine lines',
        slug: 'minimalist-geometric-triangle-003',
        originalFilename: 'geometric_triangle_003.jpg',
        storagePath: '/uploads/tattoos/2024/01/geometric_triangle_003.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/01/geometric_triangle_003_thumb.jpg',
          medium: '/uploads/tattoos/2024/01/geometric_triangle_003_medium.jpg',
          large: '/uploads/tattoos/2024/01/geometric_triangle_003_large.jpg',
          original: '/uploads/tattoos/2024/01/geometric_triangle_003.jpg',
        },
        primaryColor: '#000000',
        fileSize: 845231,
        dimensions: {
          width: 1080,
          height: 1350,
          aspectRatio: 0.8,
        },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.GEOMETRIC,
        bodyPlacement: BodyPlacement.FOREARM,
        sizeCategory: SizeCategory.SMALL,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 1,
        estimatedHours: 2.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 456,
        likeCount: 34,
        shareCount: 8,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 180.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage triangle géométrique minimaliste sur avant-bras',
          en: 'Minimalist geometric triangle tattoo on forearm',
        },
        searchKeywords: ['geometric', 'triangle', 'minimalist', 'forearm', 'linework'],
        metaTitle: 'Geometric Triangle Tattoo | Minimalist Design',
        metaDescription: 'Clean and precise geometric triangle tattoo with minimalist aesthetic',
        publishedAt: DateTime.fromISO('2024-02-01T09:15:00Z'),
      },
      // Additional 27 tattoos for comprehensive portfolio
      {
        artistId: artists[3].id,
        title: 'Watercolor Hummingbird',
        description: 'Vibrant watercolor style hummingbird with splashes of color',
        slug: 'watercolor-hummingbird-004',
        originalFilename: 'watercolor_hummingbird_004.jpg',
        storagePath: '/uploads/tattoos/2024/02/watercolor_hummingbird_004.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/02/watercolor_hummingbird_004_thumb.jpg',
          medium: '/uploads/tattoos/2024/02/watercolor_hummingbird_004_medium.jpg',
          large: '/uploads/tattoos/2024/02/watercolor_hummingbird_004_large.jpg',
          original: '/uploads/tattoos/2024/02/watercolor_hummingbird_004.jpg',
        },
        primaryColor: '#00C9FF',
        fileSize: 1956234,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.WATERCOLOR,
        bodyPlacement: BodyPlacement.SHOULDER,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.COLOR,
        sessionCount: 2,
        estimatedHours: 5.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 623,
        likeCount: 52,
        shareCount: 14,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 480.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage colibri aquarelle sur épaule',
          en: 'Watercolor hummingbird tattoo on shoulder',
        },
        searchKeywords: ['watercolor', 'bird', 'hummingbird', 'colorful', 'shoulder'],
        metaTitle: 'Watercolor Hummingbird Tattoo | Artistic Design',
        metaDescription: 'Beautiful watercolor hummingbird with vibrant color splashes',
        publishedAt: DateTime.fromISO('2024-02-05T14:30:00Z'),
      },
      {
        artistId: artists[4].id,
        title: 'Polynesian Tribal Half Sleeve',
        description: 'Traditional Polynesian tribal patterns covering upper arm',
        slug: 'polynesian-tribal-half-sleeve-005',
        originalFilename: 'polynesian_tribal_005.jpg',
        storagePath: '/uploads/tattoos/2024/02/polynesian_tribal_005.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/02/polynesian_tribal_005_thumb.jpg',
          medium: '/uploads/tattoos/2024/02/polynesian_tribal_005_medium.jpg',
          large: '/uploads/tattoos/2024/02/polynesian_tribal_005_large.jpg',
          original: '/uploads/tattoos/2024/02/polynesian_tribal_005.jpg',
        },
        primaryColor: '#1C2833',
        fileSize: 2134567,
        dimensions: { width: 1920, height: 2560, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.TRIBAL,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 3,
        estimatedHours: 10.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1134,
        likeCount: 98,
        shareCount: 27,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1200.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage tribal polynésien demi-manche',
          en: 'Polynesian tribal half sleeve tattoo',
        },
        searchKeywords: ['tribal', 'polynesian', 'sleeve', 'traditional', 'black'],
        metaTitle: 'Polynesian Tribal Sleeve | Traditional Tattoo',
        metaDescription: 'Authentic Polynesian tribal half sleeve with traditional patterns',
        publishedAt: DateTime.fromISO('2024-02-10T11:00:00Z'),
      },
      {
        artistId: artists[5].id,
        title: 'Fine Line Lotus Mandala',
        description: 'Delicate fine line lotus flower with mandala details',
        slug: 'fine-line-lotus-mandala-006',
        originalFilename: 'fine_line_lotus_006.jpg',
        storagePath: '/uploads/tattoos/2024/02/fine_line_lotus_006.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/02/fine_line_lotus_006_thumb.jpg',
          medium: '/uploads/tattoos/2024/02/fine_line_lotus_006_medium.jpg',
          large: '/uploads/tattoos/2024/02/fine_line_lotus_006_large.jpg',
          original: '/uploads/tattoos/2024/02/fine_line_lotus_006.jpg',
        },
        primaryColor: '#333333',
        fileSize: 1245678,
        dimensions: { width: 1080, height: 1440, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.MINIMALIST,
        bodyPlacement: BodyPlacement.BACK,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 2,
        estimatedHours: 4.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 789,
        likeCount: 71,
        shareCount: 19,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 420.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage lotus mandala ligne fine sur dos',
          en: 'Fine line lotus mandala tattoo on back',
        },
        searchKeywords: ['fine line', 'lotus', 'mandala', 'minimalist', 'back'],
        metaTitle: 'Fine Line Lotus Mandala | Minimalist Tattoo',
        metaDescription: 'Delicate fine line lotus with intricate mandala details',
        publishedAt: DateTime.fromISO('2024-02-15T16:20:00Z'),
      },
      {
        artistId: artists[6].id,
        title: 'Neo Traditional Eagle',
        description: 'Bold neo traditional eagle with modern color palette',
        slug: 'neo-traditional-eagle-007',
        originalFilename: 'neo_traditional_eagle_007.jpg',
        storagePath: '/uploads/tattoos/2024/02/neo_traditional_eagle_007.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/02/neo_traditional_eagle_007_thumb.jpg',
          medium: '/uploads/tattoos/2024/02/neo_traditional_eagle_007_medium.jpg',
          large: '/uploads/tattoos/2024/02/neo_traditional_eagle_007_large.jpg',
          original: '/uploads/tattoos/2024/02/neo_traditional_eagle_007.jpg',
        },
        primaryColor: '#FF8E53',
        fileSize: 2345678,
        dimensions: { width: 1920, height: 2560, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.NEO_TRADITIONAL,
        bodyPlacement: BodyPlacement.CHEST,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 4,
        estimatedHours: 14.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1456,
        likeCount: 124,
        shareCount: 35,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1650.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage aigle néo-traditionnel sur torse',
          en: 'Neo traditional eagle tattoo on chest',
        },
        searchKeywords: ['neo traditional', 'eagle', 'bird', 'chest', 'colorful'],
        metaTitle: 'Neo Traditional Eagle Tattoo | Bold Design',
        metaDescription: 'Stunning neo traditional eagle with vibrant modern colors',
        publishedAt: DateTime.fromISO('2024-02-20T13:45:00Z'),
      },
      {
        artistId: artists[7].id,
        title: 'Botanical Peony Thigh Piece',
        description: 'Realistic botanical peony flowers covering thigh',
        slug: 'botanical-peony-thigh-008',
        originalFilename: 'botanical_peony_008.jpg',
        storagePath: '/uploads/tattoos/2024/02/botanical_peony_008.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/02/botanical_peony_008_thumb.jpg',
          medium: '/uploads/tattoos/2024/02/botanical_peony_008_medium.jpg',
          large: '/uploads/tattoos/2024/02/botanical_peony_008_large.jpg',
          original: '/uploads/tattoos/2024/02/botanical_peony_008.jpg',
        },
        primaryColor: '#E91E63',
        fileSize: 2567890,
        dimensions: { width: 1440, height: 2160, aspectRatio: 0.67 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.THIGH,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 3,
        estimatedHours: 11.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 967,
        likeCount: 88,
        shareCount: 21,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1380.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage pivoine botanique réaliste sur cuisse',
          en: 'Realistic botanical peony tattoo on thigh',
        },
        searchKeywords: ['botanical', 'peony', 'flowers', 'realistic', 'thigh'],
        metaTitle: 'Botanical Peony Tattoo | Realistic Floral',
        metaDescription: 'Beautiful realistic peony flowers with botanical details',
        publishedAt: DateTime.fromISO('2024-02-25T10:30:00Z'),
      },
      {
        artistId: artists[8].id,
        title: 'Sacred Geometry Dotwork',
        description: 'Intricate sacred geometry pattern created with dotwork technique',
        slug: 'sacred-geometry-dotwork-009',
        originalFilename: 'sacred_geometry_009.jpg',
        storagePath: '/uploads/tattoos/2024/03/sacred_geometry_009.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/sacred_geometry_009_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/sacred_geometry_009_medium.jpg',
          large: '/uploads/tattoos/2024/03/sacred_geometry_009_large.jpg',
          original: '/uploads/tattoos/2024/03/sacred_geometry_009.jpg',
        },
        primaryColor: '#8E44AD',
        fileSize: 1834567,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.GEOMETRIC,
        bodyPlacement: BodyPlacement.FOREARM,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 3,
        estimatedHours: 8.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 734,
        likeCount: 65,
        shareCount: 16,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 720.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage géométrie sacrée dotwork sur avant-bras',
          en: 'Sacred geometry dotwork tattoo on forearm',
        },
        searchKeywords: ['sacred geometry', 'dotwork', 'geometric', 'mandala', 'forearm'],
        metaTitle: 'Sacred Geometry Dotwork | Geometric Tattoo',
        metaDescription: 'Intricate sacred geometry created with precise dotwork technique',
        publishedAt: DateTime.fromISO('2024-03-01T15:00:00Z'),
      },
      {
        artistId: artists[9].id,
        title: 'Japanese Koi Fish Sleeve',
        description: 'Traditional Japanese koi fish with waves and cherry blossoms',
        slug: 'japanese-koi-sleeve-010',
        originalFilename: 'japanese_koi_010.jpg',
        storagePath: '/uploads/tattoos/2024/03/japanese_koi_010.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/japanese_koi_010_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/japanese_koi_010_medium.jpg',
          large: '/uploads/tattoos/2024/03/japanese_koi_010_large.jpg',
          original: '/uploads/tattoos/2024/03/japanese_koi_010.jpg',
        },
        primaryColor: '#C0392B',
        fileSize: 2789012,
        dimensions: { width: 1920, height: 2880, aspectRatio: 0.67 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.JAPANESE,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.EXTRA_LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 6,
        estimatedHours: 20.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1834,
        likeCount: 156,
        shareCount: 42,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 2400.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage carpe koi japonaise manche complète',
          en: 'Japanese koi fish full sleeve tattoo',
        },
        searchKeywords: ['japanese', 'koi', 'fish', 'sleeve', 'traditional', 'irezumi'],
        metaTitle: 'Japanese Koi Sleeve | Traditional Irezumi',
        metaDescription: 'Authentic Japanese koi fish full sleeve with waves and cherry blossoms',
        publishedAt: DateTime.fromISO('2024-03-05T12:15:00Z'),
      },
      {
        artistId: artists[10].id,
        title: 'Biomechanical Arm Panel',
        description: 'Futuristic biomechanical design with mechanical elements',
        slug: 'biomechanical-arm-panel-011',
        originalFilename: 'biomechanical_011.jpg',
        storagePath: '/uploads/tattoos/2024/03/biomechanical_011.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/biomechanical_011_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/biomechanical_011_medium.jpg',
          large: '/uploads/tattoos/2024/03/biomechanical_011_large.jpg',
          original: '/uploads/tattoos/2024/03/biomechanical_011.jpg',
        },
        primaryColor: '#7F8C8D',
        fileSize: 2145678,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 4,
        estimatedHours: 13.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 823,
        likeCount: 72,
        shareCount: 18,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1450.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage biomécanique panneau bras',
          en: 'Biomechanical arm panel tattoo',
        },
        searchKeywords: ['biomechanical', 'mechanical', 'futuristic', 'arm', 'realistic'],
        metaTitle: 'Biomechanical Arm Tattoo | Futuristic Design',
        metaDescription:
          'Detailed biomechanical tattoo with mechanical elements and realistic shading',
        publishedAt: DateTime.fromISO('2024-03-10T14:45:00Z'),
      },
      {
        artistId: artists[11].id,
        title: 'Abstract Brush Stroke',
        description: 'Modern abstract design with bold brush stroke aesthetics',
        slug: 'abstract-brush-stroke-012',
        originalFilename: 'abstract_brush_012.jpg',
        storagePath: '/uploads/tattoos/2024/03/abstract_brush_012.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/abstract_brush_012_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/abstract_brush_012_medium.jpg',
          large: '/uploads/tattoos/2024/03/abstract_brush_012_large.jpg',
          original: '/uploads/tattoos/2024/03/abstract_brush_012.jpg',
        },
        primaryColor: '#E74C3C',
        fileSize: 1567890,
        dimensions: { width: 1080, height: 1440, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.ABSTRACT,
        bodyPlacement: BodyPlacement.RIBS,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.COLOR,
        sessionCount: 2,
        estimatedHours: 6.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 512,
        likeCount: 43,
        shareCount: 9,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 540.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage abstrait coup de pinceau sur côtes',
          en: 'Abstract brush stroke tattoo on ribs',
        },
        searchKeywords: ['abstract', 'modern', 'brush stroke', 'ribs', 'colorful'],
        metaTitle: 'Abstract Brush Stroke Tattoo | Modern Art',
        metaDescription: 'Bold modern abstract tattoo with artistic brush stroke design',
        publishedAt: DateTime.fromISO('2024-03-15T11:30:00Z'),
      },
      {
        artistId: artists[12].id,
        title: 'Traditional American Anchor',
        description: 'Classic American traditional anchor with rope and banner',
        slug: 'traditional-american-anchor-013',
        originalFilename: 'american_anchor_013.jpg',
        storagePath: '/uploads/tattoos/2024/03/american_anchor_013.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/american_anchor_013_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/american_anchor_013_medium.jpg',
          large: '/uploads/tattoos/2024/03/american_anchor_013_large.jpg',
          original: '/uploads/tattoos/2024/03/american_anchor_013.jpg',
        },
        primaryColor: '#FF6B35',
        fileSize: 1234567,
        dimensions: { width: 1080, height: 1620, aspectRatio: 0.67 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.TRADITIONAL,
        bodyPlacement: BodyPlacement.FOREARM,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.COLOR,
        sessionCount: 1,
        estimatedHours: 3.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 689,
        likeCount: 58,
        shareCount: 13,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 320.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage ancre américaine traditionnelle sur avant-bras',
          en: 'Traditional American anchor tattoo on forearm',
        },
        searchKeywords: ['traditional', 'anchor', 'american', 'nautical', 'forearm'],
        metaTitle: 'American Traditional Anchor | Classic Tattoo',
        metaDescription: 'Bold American traditional anchor with rope and banner design',
        publishedAt: DateTime.fromISO('2024-03-20T16:00:00Z'),
      },
      {
        artistId: artists[13].id,
        title: 'Script Lettering Quote',
        description: 'Elegant script lettering with motivational quote',
        slug: 'script-lettering-quote-014',
        originalFilename: 'script_lettering_014.jpg',
        storagePath: '/uploads/tattoos/2024/03/script_lettering_014.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/03/script_lettering_014_thumb.jpg',
          medium: '/uploads/tattoos/2024/03/script_lettering_014_medium.jpg',
          large: '/uploads/tattoos/2024/03/script_lettering_014_large.jpg',
          original: '/uploads/tattoos/2024/03/script_lettering_014.jpg',
        },
        primaryColor: '#000000',
        fileSize: 956789,
        dimensions: { width: 1080, height: 1350, aspectRatio: 0.8 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.LETTERING,
        bodyPlacement: BodyPlacement.RIBS,
        sizeCategory: SizeCategory.SMALL,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 1,
        estimatedHours: 2.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 423,
        likeCount: 36,
        shareCount: 7,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 220.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage calligraphie citation sur côtes',
          en: 'Script lettering quote tattoo on ribs',
        },
        searchKeywords: ['lettering', 'script', 'quote', 'text', 'calligraphy'],
        metaTitle: 'Script Lettering Tattoo | Elegant Typography',
        metaDescription: 'Beautiful script lettering with elegant calligraphy design',
        publishedAt: DateTime.fromISO('2024-03-25T13:20:00Z'),
      },
      {
        artistId: artists[14].id,
        title: 'Hyperrealistic Eye Portrait',
        description: 'Photorealistic eye portrait with incredible detail',
        slug: 'hyperrealistic-eye-portrait-015',
        originalFilename: 'hyperrealistic_eye_015.jpg',
        storagePath: '/uploads/tattoos/2024/04/hyperrealistic_eye_015.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/hyperrealistic_eye_015_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/hyperrealistic_eye_015_medium.jpg',
          large: '/uploads/tattoos/2024/04/hyperrealistic_eye_015_large.jpg',
          original: '/uploads/tattoos/2024/04/hyperrealistic_eye_015.jpg',
        },
        primaryColor: '#4A90E2',
        fileSize: 2234567,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.SHOULDER,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.COLOR,
        sessionCount: 3,
        estimatedHours: 9.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1245,
        likeCount: 112,
        shareCount: 29,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 950.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage œil hyperréaliste sur épaule',
          en: 'Hyperrealistic eye portrait tattoo on shoulder',
        },
        searchKeywords: ['hyperrealism', 'eye', 'portrait', 'realistic', 'shoulder'],
        metaTitle: 'Hyperrealistic Eye Tattoo | Portrait Detail',
        metaDescription: 'Stunning hyperrealistic eye portrait with incredible photographic detail',
        publishedAt: DateTime.fromISO('2024-04-01T10:45:00Z'),
      },
      {
        artistId: artists[15].id,
        title: 'Ornamental Jewelry Armband',
        description: 'Intricate ornamental jewelry-inspired armband design',
        slug: 'ornamental-jewelry-armband-016',
        originalFilename: 'ornamental_armband_016.jpg',
        storagePath: '/uploads/tattoos/2024/04/ornamental_armband_016.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/ornamental_armband_016_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/ornamental_armband_016_medium.jpg',
          large: '/uploads/tattoos/2024/04/ornamental_armband_016_large.jpg',
          original: '/uploads/tattoos/2024/04/ornamental_armband_016.jpg',
        },
        primaryColor: '#D4AF37',
        fileSize: 1678901,
        dimensions: { width: 1440, height: 1080, aspectRatio: 1.33 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.ORNAMENTAL,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 2,
        estimatedHours: 5.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 645,
        likeCount: 55,
        shareCount: 14,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 490.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage bracelet ornemental bijou sur bras',
          en: 'Ornamental jewelry armband tattoo',
        },
        searchKeywords: ['ornamental', 'jewelry', 'armband', 'decorative', 'arm'],
        metaTitle: 'Ornamental Jewelry Armband | Decorative Tattoo',
        metaDescription: 'Intricate ornamental armband with jewelry-inspired design',
        publishedAt: DateTime.fromISO('2024-04-05T15:30:00Z'),
      },
      {
        artistId: artists[16].id,
        title: 'Blackwork Mandala Back',
        description: 'Bold blackwork mandala covering upper back',
        slug: 'blackwork-mandala-back-017',
        originalFilename: 'blackwork_mandala_017.jpg',
        storagePath: '/uploads/tattoos/2024/04/blackwork_mandala_017.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/blackwork_mandala_017_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/blackwork_mandala_017_medium.jpg',
          large: '/uploads/tattoos/2024/04/blackwork_mandala_017_large.jpg',
          original: '/uploads/tattoos/2024/04/blackwork_mandala_017.jpg',
        },
        primaryColor: '#0B0B0B',
        fileSize: 2456789,
        dimensions: { width: 1920, height: 2560, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.BLACKWORK,
        bodyPlacement: BodyPlacement.BACK,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 4,
        estimatedHours: 12.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1123,
        likeCount: 97,
        shareCount: 24,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1320.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage mandala blackwork sur dos',
          en: 'Blackwork mandala tattoo on back',
        },
        searchKeywords: ['blackwork', 'mandala', 'back', 'bold', 'geometric'],
        metaTitle: 'Blackwork Mandala Back Tattoo | Bold Design',
        metaDescription: 'Impressive blackwork mandala covering upper back with bold solid fills',
        publishedAt: DateTime.fromISO('2024-04-10T12:00:00Z'),
      },
      {
        artistId: artists[17].id,
        title: 'Celtic Knot Armband',
        description: 'Traditional Celtic knot pattern forming complete armband',
        slug: 'celtic-knot-armband-018',
        originalFilename: 'celtic_knot_018.jpg',
        storagePath: '/uploads/tattoos/2024/04/celtic_knot_018.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/celtic_knot_018_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/celtic_knot_018_medium.jpg',
          large: '/uploads/tattoos/2024/04/celtic_knot_018_large.jpg',
          original: '/uploads/tattoos/2024/04/celtic_knot_018.jpg',
        },
        primaryColor: '#2C5F2D',
        fileSize: 1345678,
        dimensions: { width: 1440, height: 1080, aspectRatio: 1.33 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.TRIBAL,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 2,
        estimatedHours: 4.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 534,
        likeCount: 46,
        shareCount: 11,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 360.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage bracelet motif celtique sur bras',
          en: 'Celtic knot armband tattoo',
        },
        searchKeywords: ['celtic', 'knot', 'armband', 'tribal', 'traditional'],
        metaTitle: 'Celtic Knot Armband | Traditional Tattoo',
        metaDescription: 'Traditional Celtic knot pattern forming intricate armband design',
        publishedAt: DateTime.fromISO('2024-04-15T14:15:00Z'),
      },
      {
        artistId: artists[18].id,
        title: 'Dark Horror Skull',
        description: 'Dark art horror-style skull with gothic elements',
        slug: 'dark-horror-skull-019',
        originalFilename: 'dark_horror_skull_019.jpg',
        storagePath: '/uploads/tattoos/2024/04/dark_horror_skull_019.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/dark_horror_skull_019_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/dark_horror_skull_019_medium.jpg',
          large: '/uploads/tattoos/2024/04/dark_horror_skull_019_large.jpg',
          original: '/uploads/tattoos/2024/04/dark_horror_skull_019.jpg',
        },
        primaryColor: '#2C2C2C',
        fileSize: 2123456,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.LEG,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 3,
        estimatedHours: 10.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 876,
        likeCount: 79,
        shareCount: 17,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1100.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage crâne dark art horreur sur jambe',
          en: 'Dark horror skull tattoo on leg',
        },
        searchKeywords: ['horror', 'skull', 'dark art', 'gothic', 'leg'],
        metaTitle: 'Dark Horror Skull Tattoo | Gothic Design',
        metaDescription: 'Impressive dark art horror skull with intricate gothic elements',
        publishedAt: DateTime.fromISO('2024-04-20T11:45:00Z'),
      },
      {
        artistId: artists[19].id,
        title: 'Surrealist Dream Scene',
        description: 'Surrealist composition with dreamlike elements and symbolism',
        slug: 'surrealist-dream-scene-020',
        originalFilename: 'surrealist_dream_020.jpg',
        storagePath: '/uploads/tattoos/2024/04/surrealist_dream_020.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/04/surrealist_dream_020_thumb.jpg',
          medium: '/uploads/tattoos/2024/04/surrealist_dream_020_medium.jpg',
          large: '/uploads/tattoos/2024/04/surrealist_dream_020_large.jpg',
          original: '/uploads/tattoos/2024/04/surrealist_dream_020.jpg',
        },
        primaryColor: '#9B59B6',
        fileSize: 2345678,
        dimensions: { width: 1920, height: 2560, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.ABSTRACT,
        bodyPlacement: BodyPlacement.THIGH,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 4,
        estimatedHours: 13.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1034,
        likeCount: 91,
        shareCount: 22,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1480.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage surréaliste scène onirique sur cuisse',
          en: 'Surrealist dream scene tattoo on thigh',
        },
        searchKeywords: ['surrealism', 'dream', 'abstract', 'symbolic', 'thigh'],
        metaTitle: 'Surrealist Dream Scene Tattoo | Abstract Art',
        metaDescription: 'Artistic surrealist composition with dreamlike elements and symbolism',
        publishedAt: DateTime.fromISO('2024-04-25T16:30:00Z'),
      },
      {
        artistId: artists[0].id,
        title: 'Wolf Portrait Realism',
        description: 'Photorealistic wolf portrait with intense eyes',
        slug: 'wolf-portrait-realism-021',
        originalFilename: 'wolf_portrait_021.jpg',
        storagePath: '/uploads/tattoos/2024/05/wolf_portrait_021.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/wolf_portrait_021_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/wolf_portrait_021_medium.jpg',
          large: '/uploads/tattoos/2024/05/wolf_portrait_021_large.jpg',
          original: '/uploads/tattoos/2024/05/wolf_portrait_021.jpg',
        },
        primaryColor: '#6B6B6B',
        fileSize: 2456789,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.ARM,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 4,
        estimatedHours: 11.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1567,
        likeCount: 134,
        shareCount: 31,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1250.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage portrait loup réaliste sur bras',
          en: 'Realistic wolf portrait tattoo on arm',
        },
        searchKeywords: ['wolf', 'portrait', 'realistic', 'animal', 'arm'],
        metaTitle: 'Realistic Wolf Portrait | Animal Tattoo',
        metaDescription: 'Stunning photorealistic wolf portrait with incredible detail',
        publishedAt: DateTime.fromISO('2024-05-01T10:00:00Z'),
      },
      {
        artistId: artists[1].id,
        title: 'Dotwork Compass Design',
        description: 'Intricate compass created entirely with dotwork shading',
        slug: 'dotwork-compass-design-022',
        originalFilename: 'dotwork_compass_022.jpg',
        storagePath: '/uploads/tattoos/2024/05/dotwork_compass_022.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/dotwork_compass_022_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/dotwork_compass_022_medium.jpg',
          large: '/uploads/tattoos/2024/05/dotwork_compass_022_large.jpg',
          original: '/uploads/tattoos/2024/05/dotwork_compass_022.jpg',
        },
        primaryColor: '#333333',
        fileSize: 1567890,
        dimensions: { width: 1440, height: 1440, aspectRatio: 1.0 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.GEOMETRIC,
        bodyPlacement: BodyPlacement.BACK,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 3,
        estimatedHours: 7.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 712,
        likeCount: 63,
        shareCount: 15,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 680.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage boussole dotwork sur dos',
          en: 'Dotwork compass tattoo on back',
        },
        searchKeywords: ['dotwork', 'compass', 'geometric', 'navigation', 'back'],
        metaTitle: 'Dotwork Compass Tattoo | Geometric Design',
        metaDescription: 'Intricate compass design created entirely with dotwork shading technique',
        publishedAt: DateTime.fromISO('2024-05-05T13:30:00Z'),
      },
      {
        artistId: artists[2].id,
        title: 'Mountain Range Minimalist',
        description: 'Simple minimalist mountain range with sun',
        slug: 'mountain-range-minimalist-023',
        originalFilename: 'mountain_minimalist_023.jpg',
        storagePath: '/uploads/tattoos/2024/05/mountain_minimalist_023.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/mountain_minimalist_023_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/mountain_minimalist_023_medium.jpg',
          large: '/uploads/tattoos/2024/05/mountain_minimalist_023_large.jpg',
          original: '/uploads/tattoos/2024/05/mountain_minimalist_023.jpg',
        },
        primaryColor: '#000000',
        fileSize: 834567,
        dimensions: { width: 1080, height: 810, aspectRatio: 1.33 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.MINIMALIST,
        bodyPlacement: BodyPlacement.FOREARM,
        sizeCategory: SizeCategory.SMALL,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 1,
        estimatedHours: 1.5,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 389,
        likeCount: 32,
        shareCount: 6,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 140.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage montagnes minimaliste sur avant-bras',
          en: 'Minimalist mountain range tattoo on forearm',
        },
        searchKeywords: ['minimalist', 'mountain', 'nature', 'simple', 'forearm'],
        metaTitle: 'Minimalist Mountain Range | Simple Tattoo',
        metaDescription: 'Clean minimalist mountain range design with simple linework',
        publishedAt: DateTime.fromISO('2024-05-10T15:45:00Z'),
      },
      {
        artistId: artists[3].id,
        title: 'Colorful Phoenix Rising',
        description: 'Vibrant watercolor phoenix with flames and color splashes',
        slug: 'colorful-phoenix-rising-024',
        originalFilename: 'phoenix_watercolor_024.jpg',
        storagePath: '/uploads/tattoos/2024/05/phoenix_watercolor_024.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/phoenix_watercolor_024_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/phoenix_watercolor_024_medium.jpg',
          large: '/uploads/tattoos/2024/05/phoenix_watercolor_024_large.jpg',
          original: '/uploads/tattoos/2024/05/phoenix_watercolor_024.jpg',
        },
        primaryColor: '#FF4500',
        fileSize: 2789012,
        dimensions: { width: 1920, height: 2880, aspectRatio: 0.67 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.WATERCOLOR,
        bodyPlacement: BodyPlacement.BACK,
        sizeCategory: SizeCategory.EXTRA_LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 5,
        estimatedHours: 16.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1923,
        likeCount: 167,
        shareCount: 45,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 2100.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage phénix aquarelle coloré sur dos',
          en: 'Colorful watercolor phoenix tattoo on back',
        },
        searchKeywords: ['phoenix', 'watercolor', 'colorful', 'mythical', 'back'],
        metaTitle: 'Watercolor Phoenix Tattoo | Vibrant Design',
        metaDescription:
          'Stunning watercolor phoenix with vibrant flames and artistic color splashes',
        publishedAt: DateTime.fromISO('2024-05-15T12:20:00Z'),
      },
      {
        artistId: artists[4].id,
        title: 'Maori Tribal Chest',
        description: 'Traditional Maori tribal patterns covering chest',
        slug: 'maori-tribal-chest-025',
        originalFilename: 'maori_tribal_025.jpg',
        storagePath: '/uploads/tattoos/2024/05/maori_tribal_025.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/maori_tribal_025_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/maori_tribal_025_medium.jpg',
          large: '/uploads/tattoos/2024/05/maori_tribal_025_large.jpg',
          original: '/uploads/tattoos/2024/05/maori_tribal_025.jpg',
        },
        primaryColor: '#000000',
        fileSize: 2456789,
        dimensions: { width: 1920, height: 2560, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.TRIBAL,
        bodyPlacement: BodyPlacement.CHEST,
        sizeCategory: SizeCategory.EXTRA_LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 5,
        estimatedHours: 18.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1678,
        likeCount: 143,
        shareCount: 38,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 2250.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage tribal maori sur torse',
          en: 'Maori tribal chest tattoo',
        },
        searchKeywords: ['maori', 'tribal', 'chest', 'traditional', 'polynesian'],
        metaTitle: 'Maori Tribal Chest Tattoo | Traditional Design',
        metaDescription: 'Authentic Maori tribal patterns with traditional cultural symbolism',
        publishedAt: DateTime.fromISO('2024-05-20T14:00:00Z'),
      },
      {
        artistId: artists[5].id,
        title: 'Delicate Floral Wrist',
        description: 'Fine line delicate floral design wrapping around wrist',
        slug: 'delicate-floral-wrist-026',
        originalFilename: 'floral_wrist_026.jpg',
        storagePath: '/uploads/tattoos/2024/05/floral_wrist_026.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/05/floral_wrist_026_thumb.jpg',
          medium: '/uploads/tattoos/2024/05/floral_wrist_026_medium.jpg',
          large: '/uploads/tattoos/2024/05/floral_wrist_026_large.jpg',
          original: '/uploads/tattoos/2024/05/floral_wrist_026.jpg',
        },
        primaryColor: '#FFB6C1',
        fileSize: 945678,
        dimensions: { width: 1080, height: 1080, aspectRatio: 1.0 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.MINIMALIST,
        bodyPlacement: BodyPlacement.WRIST,
        sizeCategory: SizeCategory.SMALL,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 1,
        estimatedHours: 2.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 456,
        likeCount: 41,
        shareCount: 9,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 160.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage floral délicat ligne fine sur poignet',
          en: 'Delicate fine line floral tattoo on wrist',
        },
        searchKeywords: ['fine line', 'floral', 'wrist', 'delicate', 'minimalist'],
        metaTitle: 'Delicate Floral Wrist Tattoo | Fine Line',
        metaDescription: 'Elegant fine line floral design wrapping delicately around wrist',
        publishedAt: DateTime.fromISO('2024-05-25T11:15:00Z'),
      },
      {
        artistId: artists[6].id,
        title: 'Neo Traditional Peony',
        description: 'Bold neo traditional peony with rich colors',
        slug: 'neo-traditional-peony-027',
        originalFilename: 'neo_peony_027.jpg',
        storagePath: '/uploads/tattoos/2024/06/neo_peony_027.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/06/neo_peony_027_thumb.jpg',
          medium: '/uploads/tattoos/2024/06/neo_peony_027_medium.jpg',
          large: '/uploads/tattoos/2024/06/neo_peony_027_large.jpg',
          original: '/uploads/tattoos/2024/06/neo_peony_027.jpg',
        },
        primaryColor: '#E91E63',
        fileSize: 2123456,
        dimensions: { width: 1440, height: 1920, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.NEO_TRADITIONAL,
        bodyPlacement: BodyPlacement.THIGH,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 3,
        estimatedHours: 10.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: false,
        viewCount: 934,
        likeCount: 82,
        shareCount: 20,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1150.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage pivoine néo-traditionnelle sur cuisse',
          en: 'Neo traditional peony tattoo on thigh',
        },
        searchKeywords: ['neo traditional', 'peony', 'flower', 'colorful', 'thigh'],
        metaTitle: 'Neo Traditional Peony Tattoo | Floral Design',
        metaDescription: 'Bold neo traditional peony with rich vibrant colors',
        publishedAt: DateTime.fromISO('2024-06-01T13:45:00Z'),
      },
      {
        artistId: artists[7].id,
        title: 'Botanical Lavender Branch',
        description: 'Realistic botanical illustration of lavender branch',
        slug: 'botanical-lavender-branch-028',
        originalFilename: 'lavender_botanical_028.jpg',
        storagePath: '/uploads/tattoos/2024/06/lavender_botanical_028.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/06/lavender_botanical_028_thumb.jpg',
          medium: '/uploads/tattoos/2024/06/lavender_botanical_028_medium.jpg',
          large: '/uploads/tattoos/2024/06/lavender_botanical_028_large.jpg',
          original: '/uploads/tattoos/2024/06/lavender_botanical_028.jpg',
        },
        primaryColor: '#967BB6',
        fileSize: 1678901,
        dimensions: { width: 1080, height: 1620, aspectRatio: 0.67 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.REALISTIC,
        bodyPlacement: BodyPlacement.FOREARM,
        sizeCategory: SizeCategory.MEDIUM,
        colorType: ColorType.COLOR,
        sessionCount: 2,
        estimatedHours: 5.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: false,
        isPortfolioHighlight: false,
        viewCount: 567,
        likeCount: 48,
        shareCount: 11,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 450.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage branche lavande botanique sur avant-bras',
          en: 'Botanical lavender branch tattoo on forearm',
        },
        searchKeywords: ['botanical', 'lavender', 'flowers', 'realistic', 'forearm'],
        metaTitle: 'Botanical Lavender Tattoo | Realistic Floral',
        metaDescription: 'Beautiful realistic botanical illustration of lavender branch',
        publishedAt: DateTime.fromISO('2024-06-05T15:30:00Z'),
      },
      {
        artistId: artists[8].id,
        title: 'Metatron Cube Geometry',
        description: 'Sacred geometry Metatrons Cube with intricate details',
        slug: 'metatron-cube-geometry-029',
        originalFilename: 'metatron_cube_029.jpg',
        storagePath: '/uploads/tattoos/2024/06/metatron_cube_029.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/06/metatron_cube_029_thumb.jpg',
          medium: '/uploads/tattoos/2024/06/metatron_cube_029_medium.jpg',
          large: '/uploads/tattoos/2024/06/metatron_cube_029_large.jpg',
          original: '/uploads/tattoos/2024/06/metatron_cube_029.jpg',
        },
        primaryColor: '#4169E1',
        fileSize: 1923456,
        dimensions: { width: 1440, height: 1440, aspectRatio: 1.0 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.GEOMETRIC,
        bodyPlacement: BodyPlacement.CHEST,
        sizeCategory: SizeCategory.LARGE,
        colorType: ColorType.BLACK_AND_GREY,
        sessionCount: 4,
        estimatedHours: 12.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 1234,
        likeCount: 108,
        shareCount: 28,
        allowsInquiries: true,
        showsPricing: true,
        priceEstimate: 1400.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage cube de Métatron géométrie sacrée sur torse',
          en: 'Metatrons Cube sacred geometry tattoo on chest',
        },
        searchKeywords: ['sacred geometry', 'metatron', 'geometric', 'chest', 'spiritual'],
        metaTitle: 'Metatrons Cube Tattoo | Sacred Geometry',
        metaDescription: 'Intricate Metatrons Cube design with precise sacred geometry',
        publishedAt: DateTime.fromISO('2024-06-10T12:00:00Z'),
      },
      {
        artistId: artists[9].id,
        title: 'Japanese Dragon Back',
        description: 'Full back traditional Japanese dragon with clouds and waves',
        slug: 'japanese-dragon-back-030',
        originalFilename: 'japanese_dragon_back_030.jpg',
        storagePath: '/uploads/tattoos/2024/06/japanese_dragon_back_030.jpg',
        imageVariants: {
          thumbnail: '/uploads/tattoos/2024/06/japanese_dragon_back_030_thumb.jpg',
          medium: '/uploads/tattoos/2024/06/japanese_dragon_back_030_medium.jpg',
          large: '/uploads/tattoos/2024/06/japanese_dragon_back_030_large.jpg',
          original: '/uploads/tattoos/2024/06/japanese_dragon_back_030.jpg',
        },
        primaryColor: '#8B0000',
        fileSize: 3234567,
        dimensions: { width: 2160, height: 2880, aspectRatio: 0.75 },
        contentType: 'image/jpeg',
        tattooStyle: TattooStyle.JAPANESE,
        bodyPlacement: BodyPlacement.BACK,
        sizeCategory: SizeCategory.EXTRA_LARGE,
        colorType: ColorType.COLOR,
        sessionCount: 8,
        estimatedHours: 30.0,
        status: TattooStatus.PUBLISHED,
        isFeatured: true,
        isPortfolioHighlight: true,
        viewCount: 2456,
        likeCount: 213,
        shareCount: 58,
        allowsInquiries: true,
        showsPricing: false,
        priceEstimate: 3500.0,
        priceCurrency: 'EUR',
        altText: {
          fr: 'Tatouage dragon japonais dos complet traditionnel',
          en: 'Traditional Japanese dragon full back tattoo',
        },
        searchKeywords: ['japanese', 'dragon', 'back', 'irezumi', 'traditional', 'full back'],
        metaTitle: 'Japanese Dragon Back Tattoo | Full Irezumi',
        metaDescription:
          'Magnificent traditional Japanese dragon covering full back with clouds and waves',
        publishedAt: DateTime.fromISO('2024-06-15T10:30:00Z'),
      },
    ]

    // Create the tattoos
    const createdTattoos = []
    for (const tattooData of sampleTattoos) {
      const tattoo = await Tattoo.create(tattooData)
      createdTattoos.push(tattoo)
    }

    // Associate tags with tattoos
    if (styleTags.length > 0 && subjectTags.length > 0 && bodyPartTags.length > 0) {
      // Tattoo 1: Dragon Traditional
      await createdTattoos[0].related('tags').attach({
        [styleTags[0].id]: {
          // Traditional
          relevance_score: 1.0,
          is_primary: true,
          assignment_type: 'manual',
          is_approved: true,
        },
        [subjectTags.find((t) => t.slug === 'dragons')?.id || subjectTags[0].id]: {
          // Dragons
          relevance_score: 0.95,
          is_primary: false,
          assignment_type: 'manual',
          is_approved: true,
        },
        [bodyPartTags.find((t) => t.slug === 'arm')?.id || bodyPartTags[0].id]: {
          // Arm
          relevance_score: 0.9,
          is_primary: false,
          assignment_type: 'manual',
          is_approved: true,
        },
      })

      // Tattoo 2: Rose Realistic
      await createdTattoos[1].related('tags').attach({
        [styleTags.find((t) => t.slug === 'realistic')?.id || styleTags[1].id]: {
          // Realistic
          relevance_score: 1.0,
          is_primary: true,
          assignment_type: 'manual',
          is_approved: true,
        },
        [subjectTags.find((t) => t.slug === 'flowers')?.id || subjectTags[1].id]: {
          // Flowers
          relevance_score: 0.95,
          is_primary: false,
          assignment_type: 'manual',
          is_approved: true,
        },
      })

      // Tattoo 3: Geometric Triangle
      await createdTattoos[2].related('tags').attach({
        [styleTags.find((t) => t.slug === 'geometric')?.id || styleTags[2].id]: {
          // Geometric
          relevance_score: 1.0,
          is_primary: true,
          assignment_type: 'manual',
          is_approved: true,
        },
      })

      // Update engagement scores
      for (const tattoo of createdTattoos) {
        await tattoo.updateEngagement()
      }

      // Update tag usage counts
      const usedTags = await Tag.query().whereHas('tattoos', (query) => {
        query.whereIn(
          'tattoo_id',
          createdTattoos.map((t) => t.id)
        )
      })

      for (const tag of usedTags) {
        await tag.incrementUsage()
      }
    }

    console.log(`Created ${createdTattoos.length} sample tattoos with tag associations`)
  }
}
