import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import ContactInquiry from '#models/contact_inquiry'
import Artist from '#models/artist'
import Tattoo from '#models/tattoo'
import { InquiryStatus, ProjectType, InquirySource } from '#models/contact_inquiry'

export default class extends BaseSeeder {
  async run() {
    // Get some artists and tattoos for relationships
    const artists = await Artist.query().limit(10)
    const tattoos = await Tattoo.query().limit(10)

    if (artists.length === 0) {
      console.log('No artists found. Please run artist seeder first.')
      return
    }

    const inquiries = [
      // Pending inquiries
      {
        fullName: 'Sophie Martin',
        email: 'sophie.martin@email.com',
        phone: '+33612345001',
        subject: 'Demande de rendez-vous pour tatouage floral',
        message:
          'Bonjour, je souhaiterais prendre rendez-vous pour un tatouage de fleurs sur l\'épaule. J\'aime beaucoup votre style aquarelle.',
        projectType: ProjectType.APPOINTMENT,
        budget: '400-600€',
        preferredDate: DateTime.now().plus({ days: 15 }).toISO(),
        location: 'Paris',
        tattooStyles: ['watercolor', 'realistic'],
        size: 'medium',
        placement: 'shoulder',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=301',
          'https://picsum.photos/400/400?random=302',
        ],
        artistId: artists[0]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 8,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.100',
        userAgent:
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0',
        metadata: { utmSource: 'instagram', utmMedium: 'social' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 2 }),
      },
      {
        fullName: 'Marc Dubois',
        email: 'marc.dubois@gmail.com',
        phone: '+33612345002',
        subject: 'Demande de devis pour tatouage tribal',
        message:
          'Je suis intéressé par un tatouage tribal polynésien sur le bras. Pouvez-vous me donner une estimation de prix et de durée?',
        projectType: ProjectType.QUOTE,
        budget: '1000-1500€',
        preferredDate: null,
        location: 'Lyon',
        tattooStyles: ['tribal', 'polynesian'],
        size: 'large',
        placement: 'arm',
        hasExistingTattoos: false,
        referenceImages: ['https://picsum.photos/400/400?random=303'],
        artistId: artists[1]?.id || null,
        tattooId: tattoos[0]?.id || null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 6,
        isRead: false,
        isStarred: true,
        ipAddress: '192.168.1.101',
        userAgent:
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        metadata: { referrer: 'google' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 5 }),
      },
      {
        fullName: 'Amélie Rousseau',
        email: 'amelie.rousseau@outlook.fr',
        phone: null,
        subject: 'Question sur le style minimaliste',
        message:
          'Bonjour, je voudrais savoir si vous faites des tatouages minimalistes très fins. C\'est pour un petit motif sur le poignet.',
        projectType: ProjectType.QUESTION,
        budget: '100-200€',
        preferredDate: null,
        location: 'Marseille',
        tattooStyles: ['minimalist', 'fine_line'],
        size: 'small',
        placement: 'wrist',
        hasExistingTattoos: false,
        referenceImages: null,
        artistId: artists[2]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.QUICK_FORM,
        priority: 3,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.102',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)',
        metadata: null,
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 1 }),
      },

      // In progress inquiries
      {
        fullName: 'Thomas Bernard',
        email: 'thomas.bernard@free.fr',
        phone: '+33612345003',
        subject: 'Consultation pour tatouage réaliste',
        message:
          'Je souhaite un tatouage réaliste de portrait de mon chien. Pouvons-nous discuter du design et des détails?',
        projectType: ProjectType.CONSULTATION,
        budget: '800-1000€',
        preferredDate: DateTime.now().plus({ days: 7 }).toISO(),
        location: 'Toulouse',
        tattooStyles: ['realistic', 'portrait'],
        size: 'medium',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=304',
          'https://picsum.photos/400/400?random=305',
          'https://picsum.photos/400/400?random=306',
        ],
        artistId: artists[3]?.id || null,
        tattooId: null,
        status: InquiryStatus.IN_PROGRESS,
        source: InquirySource.WEBSITE,
        priority: 5,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.103',
        userAgent:
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        metadata: { utmSource: 'facebook', utmMedium: 'social' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ days: 1, hours: 3 }),
      },
      {
        fullName: 'Julie Lefebvre',
        email: 'julie.lefebvre@yahoo.fr',
        phone: '+33612345004',
        subject: 'Tatouage géométrique sur le dos',
        message:
          'Je recherche un artiste pour un grand tatouage géométrique sacré sur le dos. J\'ai déjà des idées précises.',
        projectType: ProjectType.CONSULTATION,
        budget: '1500-2000€',
        preferredDate: DateTime.now().plus({ days: 20 }).toISO(),
        location: 'Nice',
        tattooStyles: ['geometric', 'dotwork'],
        size: 'large',
        placement: 'back',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=307',
          'https://picsum.photos/400/400?random=308',
        ],
        artistId: artists[4]?.id || null,
        tattooId: tattoos[1]?.id || null,
        status: InquiryStatus.IN_PROGRESS,
        source: InquirySource.SOCIAL_MEDIA,
        priority: 7,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.104',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        metadata: { referrer: 'instagram' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ days: 2 }),
      },

      // Replied inquiries
      {
        fullName: 'Pierre Moreau',
        email: 'pierre.moreau@gmail.com',
        phone: '+33612345005',
        subject: 'Rendez-vous confirmé - Tatouage japonais',
        message:
          'Merci pour votre réponse ! Je confirme le rendez-vous pour le tatouage de carpe koi.',
        projectType: ProjectType.APPOINTMENT,
        budget: '2000-2500€',
        preferredDate: DateTime.now().plus({ days: 30 }).toISO(),
        location: 'Paris',
        tattooStyles: ['japanese', 'traditional'],
        size: 'extra_large',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: ['https://picsum.photos/400/400?random=309'],
        artistId: artists[5]?.id || null,
        tattooId: tattoos[2]?.id || null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.WEBSITE,
        priority: 8,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.105',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        metadata: { utmSource: 'google', utmMedium: 'cpc' },
        firstRepliedAt: DateTime.now().minus({ days: 2, hours: 12 }),
        lastRepliedAt: DateTime.now().minus({ days: 1, hours: 8 }),
        repliesCount: 2,
        createdAt: DateTime.now().minus({ days: 3 }),
      },
      {
        fullName: 'Cécile Petit',
        email: 'cecile.petit@hotmail.com',
        phone: '+33612345006',
        subject: 'Devis reçu pour tatouage aquarelle',
        message:
          'J\'ai bien reçu votre devis. Je vais réfléchir et reviens vers vous rapidement.',
        projectType: ProjectType.QUOTE,
        budget: '500-700€',
        preferredDate: null,
        location: 'Bordeaux',
        tattooStyles: ['watercolor', 'abstract'],
        size: 'medium',
        placement: 'thigh',
        hasExistingTattoos: false,
        referenceImages: [
          'https://picsum.photos/400/400?random=310',
          'https://picsum.photos/400/400?random=311',
        ],
        artistId: artists[6]?.id || null,
        tattooId: null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.REFERRAL,
        priority: 6,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.106',
        userAgent: 'Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X)',
        metadata: { referredBy: 'friend' },
        firstRepliedAt: DateTime.now().minus({ days: 1, hours: 6 }),
        lastRepliedAt: DateTime.now().minus({ days: 1, hours: 6 }),
        repliesCount: 1,
        createdAt: DateTime.now().minus({ days: 2, hours: 15 }),
      },
      {
        fullName: 'Alexandre Roux',
        email: 'alex.roux@gmail.com',
        phone: '+33612345007',
        subject: 'Informations reçues sur le blackwork',
        message:
          'Merci pour les informations. Je suis très intéressé par votre travail en blackwork.',
        projectType: ProjectType.QUESTION,
        budget: '1200-1500€',
        preferredDate: null,
        location: 'Nantes',
        tattooStyles: ['blackwork', 'geometric'],
        size: 'large',
        placement: 'back',
        hasExistingTattoos: true,
        referenceImages: ['https://picsum.photos/400/400?random=312'],
        artistId: artists[7]?.id || null,
        tattooId: tattoos[3]?.id || null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.WEBSITE,
        priority: 7,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.107',
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
        metadata: null,
        firstRepliedAt: DateTime.now().minus({ hours: 18 }),
        lastRepliedAt: DateTime.now().minus({ hours: 18 }),
        repliesCount: 1,
        createdAt: DateTime.now().minus({ days: 1, hours: 22 }),
      },

      // Closed inquiries
      {
        fullName: 'Laura Simon',
        email: 'laura.simon@orange.fr',
        phone: '+33612345008',
        subject: 'Tatouage terminé - Merci!',
        message: 'Le tatouage est magnifique, merci beaucoup pour votre travail!',
        projectType: ProjectType.APPOINTMENT,
        budget: '600-800€',
        preferredDate: DateTime.now().minus({ days: 5 }).toISO(),
        location: 'Strasbourg',
        tattooStyles: ['neo_traditional', 'colorful'],
        size: 'medium',
        placement: 'shoulder',
        hasExistingTattoos: true,
        referenceImages: null,
        artistId: artists[8]?.id || null,
        tattooId: tattoos[4]?.id || null,
        status: InquiryStatus.CLOSED,
        source: InquirySource.WEBSITE,
        priority: 5,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.108',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X)',
        metadata: { satisfaction: 'excellent' },
        firstRepliedAt: DateTime.now().minus({ days: 8 }),
        lastRepliedAt: DateTime.now().minus({ days: 6 }),
        repliesCount: 4,
        createdAt: DateTime.now().minus({ days: 10 }),
      },
      {
        fullName: 'Vincent Laurent',
        email: 'vincent.laurent@laposte.net',
        phone: '+33612345009',
        subject: 'Projet annulé',
        message: 'Désolé, je dois reporter mon projet de tatouage pour des raisons personnelles.',
        projectType: ProjectType.CONSULTATION,
        budget: '400-600€',
        preferredDate: null,
        location: 'Lille',
        tattooStyles: ['traditional', 'american'],
        size: 'medium',
        placement: 'forearm',
        hasExistingTattoos: false,
        referenceImages: null,
        artistId: artists[9]?.id || null,
        tattooId: null,
        status: InquiryStatus.CLOSED,
        source: InquirySource.QUICK_FORM,
        priority: 3,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.109',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        metadata: { cancelReason: 'personal' },
        firstRepliedAt: DateTime.now().minus({ days: 5 }),
        lastRepliedAt: DateTime.now().minus({ days: 4 }),
        repliesCount: 2,
        createdAt: DateTime.now().minus({ days: 7 }),
      },

      // More pending inquiries
      {
        fullName: 'Emma Garnier',
        email: 'emma.garnier@gmail.com',
        phone: '+33612345010',
        subject: 'Tatouage lettering personnalisé',
        message:
          'Je souhaiterais un tatouage de citation en calligraphie élégante sur les côtes.',
        projectType: ProjectType.QUOTE,
        budget: '200-300€',
        preferredDate: null,
        location: 'Rennes',
        tattooStyles: ['lettering', 'script'],
        size: 'small',
        placement: 'ribs',
        hasExistingTattoos: true,
        referenceImages: ['https://picsum.photos/400/400?random=313'],
        artistId: artists[0]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.SOCIAL_MEDIA,
        priority: 6,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.110',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        metadata: { utmSource: 'pinterest' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 8 }),
      },
      {
        fullName: 'Nicolas Blanc',
        email: 'nicolas.blanc@sfr.fr',
        phone: '+33612345011',
        subject: 'Rendez-vous urgent',
        message:
          'Bonjour, j\'ai un événement dans 3 semaines et je voudrais absolument un tatouage avant. Est-ce possible?',
        projectType: ProjectType.APPOINTMENT,
        budget: '500-700€',
        preferredDate: DateTime.now().plus({ days: 18 }).toISO(),
        location: 'Montpellier',
        tattooStyles: ['minimalist', 'geometric'],
        size: 'small',
        placement: 'wrist',
        hasExistingTattoos: false,
        referenceImages: null,
        artistId: artists[1]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 9,
        isRead: false,
        isStarred: true,
        ipAddress: '192.168.1.111',
        userAgent: 'Mozilla/5.0 (Android 13; Mobile)',
        metadata: { urgent: true },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 3 }),
      },
      {
        fullName: 'Chloé Bonnet',
        email: 'chloe.bonnet@outlook.com',
        phone: null,
        subject: 'Tatouage ornamental bijou',
        message:
          'J\'aimerais un tatouage ornemental style bijou pour un bracelet sur le bras.',
        projectType: ProjectType.CONSULTATION,
        budget: '400-500€',
        preferredDate: DateTime.now().plus({ days: 25 }).toISO(),
        location: 'Grenoble',
        tattooStyles: ['ornamental', 'jewelry'],
        size: 'medium',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=314',
          'https://picsum.photos/400/400?random=315',
        ],
        artistId: artists[2]?.id || null,
        tattooId: tattoos[5]?.id || null,
        status: InquiryStatus.PENDING,
        source: InquirySource.REFERRAL,
        priority: 5,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.112',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)',
        metadata: { referredBy: 'artist_friend' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 12 }),
      },
      {
        fullName: 'Maxime Durand',
        email: 'maxime.durand@free.fr',
        phone: '+33612345012',
        subject: 'Tatouage biomécanique bras',
        message:
          'Je cherche un artiste spécialisé en biomécanique pour un projet de bras complet.',
        projectType: ProjectType.QUOTE,
        budget: '1500-2000€',
        preferredDate: null,
        location: 'Dijon',
        tattooStyles: ['biomechanical', 'realistic'],
        size: 'large',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=316',
          'https://picsum.photos/400/400?random=317',
          'https://picsum.photos/400/400?random=318',
        ],
        artistId: artists[3]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 6,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.113',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        metadata: null,
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 18 }),
      },
      {
        fullName: 'Sarah Lambert',
        email: 'sarah.lambert@gmail.com',
        phone: '+33612345013',
        subject: 'Question sur les soins post-tatouage',
        message:
          'Quels sont vos conseils pour les soins d\'un tatouage en couleur sur la cuisse?',
        projectType: ProjectType.QUESTION,
        budget: null,
        preferredDate: null,
        location: 'Angers',
        tattooStyles: null,
        size: null,
        placement: null,
        hasExistingTattoos: true,
        referenceImages: null,
        artistId: null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.QUICK_FORM,
        priority: 2,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.114',
        userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X)',
        metadata: null,
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 6 }),
      },

      // More in progress inquiries
      {
        fullName: 'Julien Mercier',
        email: 'julien.mercier@yahoo.fr',
        phone: '+33612345014',
        subject: 'Projet tatouage mandala',
        message:
          'Je travaille avec vous sur un projet de mandala. Quand pouvons-nous finaliser le design?',
        projectType: ProjectType.CONSULTATION,
        budget: '800-1000€',
        preferredDate: DateTime.now().plus({ days: 10 }).toISO(),
        location: 'Tours',
        tattooStyles: ['geometric', 'mandala'],
        size: 'large',
        placement: 'chest',
        hasExistingTattoos: false,
        referenceImages: ['https://picsum.photos/400/400?random=319'],
        artistId: artists[4]?.id || null,
        tattooId: tattoos[6]?.id || null,
        status: InquiryStatus.IN_PROGRESS,
        source: InquirySource.WEBSITE,
        priority: 7,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.115',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0)',
        metadata: { designIterations: 3 },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ days: 4 }),
      },
      {
        fullName: 'Manon Dufour',
        email: 'manon.dufour@hotmail.fr',
        phone: '+33612345015',
        subject: 'Retouches tatouage ancien',
        message:
          'J\'ai un ancien tatouage qui nécessite des retouches. Pouvez-vous évaluer le travail nécessaire?',
        projectType: ProjectType.CONSULTATION,
        budget: '300-500€',
        preferredDate: null,
        location: 'Clermont-Ferrand',
        tattooStyles: null,
        size: 'medium',
        placement: 'shoulder',
        hasExistingTattoos: true,
        referenceImages: ['https://picsum.photos/400/400?random=320'],
        artistId: artists[5]?.id || null,
        tattooId: null,
        status: InquiryStatus.IN_PROGRESS,
        source: InquirySource.SOCIAL_MEDIA,
        priority: 5,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.116',
        userAgent: 'Mozilla/5.0 (Windows NT 11.0; Win64; x64)',
        metadata: { coverUp: false, touchUp: true },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ days: 3, hours: 8 }),
      },

      // More replied inquiries
      {
        fullName: 'Lucas Fournier',
        email: 'lucas.fournier@gmail.com',
        phone: '+33612345016',
        subject: 'Confirmation rendez-vous dragon japonais',
        message: 'Parfait, je confirme le rendez-vous pour la session de mon dos japonais.',
        projectType: ProjectType.APPOINTMENT,
        budget: '3000-4000€',
        preferredDate: DateTime.now().plus({ days: 35 }).toISO(),
        location: 'Paris',
        tattooStyles: ['japanese', 'irezumi'],
        size: 'extra_large',
        placement: 'back',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=321',
          'https://picsum.photos/400/400?random=322',
        ],
        artistId: artists[6]?.id || null,
        tattooId: tattoos[7]?.id || null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.REFERRAL,
        priority: 9,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.117',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0)',
        metadata: { multiSession: true, sessionCount: 8 },
        firstRepliedAt: DateTime.now().minus({ days: 3, hours: 14 }),
        lastRepliedAt: DateTime.now().minus({ days: 2, hours: 10 }),
        repliesCount: 3,
        createdAt: DateTime.now().minus({ days: 5 }),
      },
      {
        fullName: 'Océane Girard',
        email: 'oceane.girard@orange.fr',
        phone: '+33612345017',
        subject: 'Devis accepté - Tatouage phoenix',
        message: 'J\'accepte votre devis pour le phoenix aquarelle. Quand pouvons-nous commencer?',
        projectType: ProjectType.QUOTE,
        budget: '2000-2500€',
        preferredDate: DateTime.now().plus({ days: 28 }).toISO(),
        location: 'Lyon',
        tattooStyles: ['watercolor', 'phoenix'],
        size: 'extra_large',
        placement: 'back',
        hasExistingTattoos: false,
        referenceImages: [
          'https://picsum.photos/400/400?random=323',
          'https://picsum.photos/400/400?random=324',
        ],
        artistId: artists[7]?.id || null,
        tattooId: tattoos[8]?.id || null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.WEBSITE,
        priority: 8,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.118',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X)',
        metadata: { quoteAccepted: true },
        firstRepliedAt: DateTime.now().minus({ days: 2, hours: 18 }),
        lastRepliedAt: DateTime.now().minus({ days: 1, hours: 4 }),
        repliesCount: 2,
        createdAt: DateTime.now().minus({ days: 4, hours: 12 }),
      },
      {
        fullName: 'Antoine Moreno',
        email: 'antoine.moreno@laposte.net',
        phone: '+33612345018',
        subject: 'Informations complémentaires fournies',
        message:
          'Voici les photos supplémentaires que vous m\'avez demandées pour le projet de sleeve.',
        projectType: ProjectType.CONSULTATION,
        budget: '2500-3000€',
        preferredDate: null,
        location: 'Marseille',
        tattooStyles: ['realistic', 'portrait'],
        size: 'extra_large',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=325',
          'https://picsum.photos/400/400?random=326',
          'https://picsum.photos/400/400?random=327',
        ],
        artistId: artists[8]?.id || null,
        tattooId: null,
        status: InquiryStatus.REPLIED,
        source: InquirySource.SOCIAL_MEDIA,
        priority: 7,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.119',
        userAgent: 'Mozilla/5.0 (Android 14; Mobile)',
        metadata: { additionalPhotos: true },
        firstRepliedAt: DateTime.now().minus({ days: 1, hours: 16 }),
        lastRepliedAt: DateTime.now().minus({ hours: 20 }),
        repliesCount: 2,
        createdAt: DateTime.now().minus({ days: 3, hours: 6 }),
      },

      // More closed inquiries
      {
        fullName: 'Camille Bertrand',
        email: 'camille.bertrand@gmail.com',
        phone: '+33612345019',
        subject: 'Projet finalisé - Merci infiniment',
        message:
          'Mon tatouage est exactement ce que je voulais ! Je recommanderai vos services.',
        projectType: ProjectType.APPOINTMENT,
        budget: '700-900€',
        preferredDate: DateTime.now().minus({ days: 12 }).toISO(),
        location: 'Bordeaux',
        tattooStyles: ['ornamental', 'dotwork'],
        size: 'medium',
        placement: 'forearm',
        hasExistingTattoos: true,
        referenceImages: null,
        artistId: artists[9]?.id || null,
        tattooId: tattoos[9]?.id || null,
        status: InquiryStatus.CLOSED,
        source: InquirySource.REFERRAL,
        priority: 5,
        isRead: true,
        isStarred: true,
        ipAddress: '192.168.1.120',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        metadata: { satisfaction: 'excellent', willRecommend: true },
        firstRepliedAt: DateTime.now().minus({ days: 18 }),
        lastRepliedAt: DateTime.now().minus({ days: 13 }),
        repliesCount: 5,
        createdAt: DateTime.now().minus({ days: 20 }),
      },
      {
        fullName: 'Théo Richard',
        email: 'theo.richard@sfr.fr',
        phone: '+33612345020',
        subject: 'Ne souhaite plus de tatouage',
        message: 'Finalement j\'ai décidé de ne pas me faire tatouer. Merci quand même.',
        projectType: ProjectType.QUOTE,
        budget: '300-400€',
        preferredDate: null,
        location: 'Nantes',
        tattooStyles: ['minimalist'],
        size: 'small',
        placement: 'ankle',
        hasExistingTattoos: false,
        referenceImages: null,
        artistId: null,
        tattooId: null,
        status: InquiryStatus.CLOSED,
        source: InquirySource.QUICK_FORM,
        priority: 2,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.121',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X)',
        metadata: { cancelReason: 'changed_mind' },
        firstRepliedAt: DateTime.now().minus({ days: 9 }),
        lastRepliedAt: DateTime.now().minus({ days: 9 }),
        repliesCount: 1,
        createdAt: DateTime.now().minus({ days: 11 }),
      },

      // Remaining inquiries for variety
      {
        fullName: 'Anaïs Robert',
        email: 'anais.robert@outlook.fr',
        phone: '+33612345021',
        subject: 'Tatouage celtique traditionnel',
        message:
          'Je recherche un tatouage de nœud celtique en bracelet. Avez-vous de l\'expérience avec ce style?',
        projectType: ProjectType.QUOTE,
        budget: '350-450€',
        preferredDate: null,
        location: 'Rennes',
        tattooStyles: ['celtic', 'tribal'],
        size: 'medium',
        placement: 'arm',
        hasExistingTattoos: true,
        referenceImages: ['https://picsum.photos/400/400?random=328'],
        artistId: artists[0]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 6,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.122',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0)',
        metadata: null,
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 14 }),
      },
      {
        fullName: 'Hugo Martinez',
        email: 'hugo.martinez@free.fr',
        phone: '+33612345022',
        subject: 'Consultation tatouage surréaliste',
        message:
          'Je voudrais discuter d\'un projet de tatouage surréaliste inspiré de Dali. Êtes-vous ouvert à ce genre de projet?',
        projectType: ProjectType.CONSULTATION,
        budget: '1000-1500€',
        preferredDate: DateTime.now().plus({ days: 14 }).toISO(),
        location: 'Nice',
        tattooStyles: ['surrealism', 'abstract'],
        size: 'large',
        placement: 'thigh',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=329',
          'https://picsum.photos/400/400?random=330',
        ],
        artistId: artists[1]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.SOCIAL_MEDIA,
        priority: 7,
        isRead: false,
        isStarred: true,
        ipAddress: '192.168.1.123',
        userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_1 like Mac OS X)',
        metadata: { utmSource: 'instagram', artInspired: 'salvador_dali' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 9 }),
      },
      {
        fullName: 'Léa Fontaine',
        email: 'lea.fontaine@yahoo.fr',
        phone: null,
        subject: 'Allergie encre tatouage',
        message:
          'J\'ai des allergies cutanées. Utilisez-vous des encres hypoallergéniques?',
        projectType: ProjectType.QUESTION,
        budget: null,
        preferredDate: null,
        location: 'Toulouse',
        tattooStyles: null,
        size: null,
        placement: null,
        hasExistingTattoos: false,
        referenceImages: null,
        artistId: null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.QUICK_FORM,
        priority: 4,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.124',
        userAgent: 'Mozilla/5.0 (Android 13; Mobile)',
        metadata: { healthConcern: true },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 4 }),
      },
      {
        fullName: 'Baptiste Leroy',
        email: 'baptiste.leroy@gmail.com',
        phone: '+33612345023',
        subject: 'Tatouage dark art gothique',
        message:
          'Je suis passionné par le dark art. Pouvez-vous réaliser un crâne gothique avec des éléments macabres?',
        projectType: ProjectType.CONSULTATION,
        budget: '900-1200€',
        preferredDate: DateTime.now().plus({ days: 22 }).toISO(),
        location: 'Lille',
        tattooStyles: ['horror', 'dark_art', 'gothic'],
        size: 'large',
        placement: 'leg',
        hasExistingTattoos: true,
        referenceImages: [
          'https://picsum.photos/400/400?random=331',
          'https://picsum.photos/400/400?random=332',
        ],
        artistId: artists[2]?.id || null,
        tattooId: null,
        status: InquiryStatus.IN_PROGRESS,
        source: InquirySource.REFERRAL,
        priority: 6,
        isRead: true,
        isStarred: false,
        ipAddress: '192.168.1.125',
        userAgent: 'Mozilla/5.0 (Windows NT 11.0; Win64; x64)',
        metadata: { referredBy: 'gothic_community' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ days: 2, hours: 18 }),
      },
      {
        fullName: 'Inès Garnier',
        email: 'ines.garnier@hotmail.com',
        phone: '+33612345024',
        subject: 'Tatouage lavande botanique',
        message:
          'J\'adore les fleurs de lavande. Pouvez-vous créer un design botanique réaliste?',
        projectType: ProjectType.QUOTE,
        budget: '400-550€',
        preferredDate: null,
        location: 'Montpellier',
        tattooStyles: ['botanical', 'realistic'],
        size: 'medium',
        placement: 'forearm',
        hasExistingTattoos: false,
        referenceImages: ['https://picsum.photos/400/400?random=333'],
        artistId: artists[3]?.id || null,
        tattooId: null,
        status: InquiryStatus.PENDING,
        source: InquirySource.WEBSITE,
        priority: 6,
        isRead: false,
        isStarred: false,
        ipAddress: '192.168.1.126',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X)',
        metadata: { flowerType: 'lavender' },
        firstRepliedAt: null,
        lastRepliedAt: null,
        repliesCount: 0,
        createdAt: DateTime.now().minus({ hours: 7 }),
      },
    ]

    // Create all inquiries
    for (const inquiryData of inquiries) {
      await ContactInquiry.create(inquiryData)
    }

    console.log(`Created ${inquiries.length} contact inquiries`)
  }
}
