import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Tag from '#models/tag'

export default class extends BaseSeeder {
  async run() {
    const tags = [
      // Style tags
      {
        name: 'Traditional',
        slug: 'traditional',
        description: 'Classic tattoo style with bold lines and bright colors',
        category: 'style',
        colorCode: '#FF6B35',
        iconName: 'classic',
        isApproved: true,
        isFeatured: true,
        displayOrder: 1,
        usageCount: 150,
        popularityScore: 8.5,
      },
      {
        name: 'Neo Traditional',
        slug: 'neo-traditional',
        description: 'Modern interpretation of traditional tattoo style',
        category: 'style',
        colorCode: '#FF8E53',
        iconName: 'modern',
        isApproved: true,
        isFeatured: true,
        displayOrder: 2,
        usageCount: 120,
        popularityScore: 8.2,
      },
      {
        name: 'Realistic',
        slug: 'realistic',
        description: 'Photorealistic tattoo style',
        category: 'style',
        colorCode: '#6B73FF',
        iconName: 'photo',
        isApproved: true,
        isFeatured: true,
        displayOrder: 3,
        usageCount: 200,
        popularityScore: 9.1,
      },
      {
        name: 'Black and Grey',
        slug: 'black-and-grey',
        description: 'Monochromatic tattoo style using only black ink',
        category: 'style',
        colorCode: '#666666',
        iconName: 'monochrome',
        isApproved: true,
        isFeatured: true,
        displayOrder: 4,
        usageCount: 180,
        popularityScore: 8.7,
      },
      {
        name: 'Watercolor',
        slug: 'watercolor',
        description: 'Artistic style mimicking watercolor paintings',
        category: 'style',
        colorCode: '#00C9FF',
        iconName: 'brush',
        isApproved: true,
        isFeatured: true,
        displayOrder: 5,
        usageCount: 95,
        popularityScore: 7.8,
      },
      {
        name: 'Geometric',
        slug: 'geometric',
        description: 'Tattoos featuring geometric patterns and shapes',
        category: 'style',
        colorCode: '#FF9500',
        iconName: 'shapes',
        isApproved: true,
        isFeatured: true,
        displayOrder: 6,
        usageCount: 110,
        popularityScore: 8.0,
      },
      {
        name: 'Minimalist',
        slug: 'minimalist',
        description: 'Simple, clean tattoo designs with minimal elements',
        category: 'style',
        colorCode: '#333333',
        iconName: 'minimal',
        isApproved: true,
        isFeatured: true,
        displayOrder: 7,
        usageCount: 85,
        popularityScore: 7.5,
      },

      // Subject tags
      {
        name: 'Portraits',
        slug: 'portraits',
        description: 'Human or animal portraits',
        category: 'subject',
        colorCode: '#E74C3C',
        iconName: 'face',
        isApproved: true,
        isFeatured: true,
        displayOrder: 10,
        usageCount: 130,
        popularityScore: 8.4,
      },
      {
        name: 'Animals',
        slug: 'animals',
        description: 'Animal-themed tattoos',
        category: 'subject',
        colorCode: '#27AE60',
        iconName: 'paw',
        isApproved: true,
        isFeatured: true,
        displayOrder: 11,
        usageCount: 160,
        popularityScore: 8.6,
      },
      {
        name: 'Flowers',
        slug: 'flowers',
        description: 'Floral designs and botanical elements',
        category: 'subject',
        colorCode: '#E91E63',
        iconName: 'flower',
        isApproved: true,
        isFeatured: true,
        displayOrder: 12,
        usageCount: 140,
        popularityScore: 8.3,
      },
      {
        name: 'Skulls',
        slug: 'skulls',
        description: 'Skull and death-themed imagery',
        category: 'subject',
        colorCode: '#34495E',
        iconName: 'skull',
        isApproved: true,
        isFeatured: false,
        displayOrder: 13,
        usageCount: 90,
        popularityScore: 7.2,
      },
      {
        name: 'Dragons',
        slug: 'dragons',
        description: 'Mythical dragon designs',
        category: 'subject',
        colorCode: '#9B59B6',
        iconName: 'dragon',
        isApproved: true,
        isFeatured: true,
        displayOrder: 14,
        usageCount: 75,
        popularityScore: 7.8,
      },

      // Body part tags
      {
        name: 'Arm',
        slug: 'arm',
        description: 'Tattoos on the arm',
        category: 'body_part',
        colorCode: '#3498DB',
        iconName: 'arm',
        isApproved: true,
        isFeatured: false,
        displayOrder: 20,
        usageCount: 250,
        popularityScore: 9.0,
      },
      {
        name: 'Back',
        slug: 'back',
        description: 'Back tattoos and backpieces',
        category: 'body_part',
        colorCode: '#2ECC71',
        iconName: 'back',
        isApproved: true,
        isFeatured: false,
        displayOrder: 21,
        usageCount: 120,
        popularityScore: 8.1,
      },
      {
        name: 'Leg',
        slug: 'leg',
        description: 'Leg tattoos',
        category: 'body_part',
        colorCode: '#F39C12',
        iconName: 'leg',
        isApproved: true,
        isFeatured: false,
        displayOrder: 22,
        usageCount: 180,
        popularityScore: 8.3,
      },
      {
        name: 'Chest',
        slug: 'chest',
        description: 'Chest tattoos',
        category: 'body_part',
        colorCode: '#E67E22',
        iconName: 'chest',
        isApproved: true,
        isFeatured: false,
        displayOrder: 23,
        usageCount: 95,
        popularityScore: 7.6,
      },

      // Size tags
      {
        name: 'Small',
        slug: 'small',
        description: 'Small tattoos under 3 inches',
        category: 'size',
        colorCode: '#95A5A6',
        iconName: 'small',
        isApproved: true,
        isFeatured: false,
        displayOrder: 30,
        usageCount: 200,
        popularityScore: 8.5,
      },
      {
        name: 'Medium',
        slug: 'medium',
        description: 'Medium-sized tattoos 3-8 inches',
        category: 'size',
        colorCode: '#7F8C8D',
        iconName: 'medium',
        isApproved: true,
        isFeatured: false,
        displayOrder: 31,
        usageCount: 150,
        popularityScore: 8.0,
      },
      {
        name: 'Large',
        slug: 'large',
        description: 'Large tattoos over 8 inches',
        category: 'size',
        colorCode: '#2C3E50',
        iconName: 'large',
        isApproved: true,
        isFeatured: false,
        displayOrder: 32,
        usageCount: 100,
        popularityScore: 7.5,
      },

      // Color tags
      {
        name: 'Color',
        slug: 'color',
        description: 'Colorful tattoos with multiple colors',
        category: 'color',
        colorCode: '#FF6B6B',
        iconName: 'palette',
        isApproved: true,
        isFeatured: false,
        displayOrder: 40,
        usageCount: 170,
        popularityScore: 8.2,
      },
      {
        name: 'Black Only',
        slug: 'black-only',
        description: 'Tattoos using only black ink',
        category: 'color',
        colorCode: '#000000',
        iconName: 'ink',
        isApproved: true,
        isFeatured: false,
        displayOrder: 41,
        usageCount: 220,
        popularityScore: 8.7,
      },
    ]

    await Tag.createMany(tags)

    // Create some hierarchical tags
    const parentTags = await Tag.query().where('category', 'subject').limit(3)
    
    for (const parentTag of parentTags) {
      await Tag.create({
        name: `${parentTag.name} Detailed`,
        slug: `${parentTag.slug}-detailed`,
        description: `Detailed ${parentTag.name.toLowerCase()} designs`,
        category: parentTag.category,
        parentTagId: parentTag.id,
        level: 1,
        colorCode: parentTag.colorCode,
        iconName: parentTag.iconName,
        isApproved: true,
        displayOrder: parentTag.displayOrder + 100,
        usageCount: Math.floor(parentTag.usageCount * 0.3),
        popularityScore: parentTag.popularityScore - 1.0,
      })
    }
  }
}