version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: blottr_postgres
    environment:
      POSTGRES_DB: blottr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - blottr-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blottr_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blottr.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - blottr-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  blottr-network:
    driver: bridge
