services:
  postgres:
    image: postgres:16
    container_name: blottr_postgres
    environment:
      POSTGRES_DB: blottr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - blottr-network

volumes:
  postgres_data:

networks:
  blottr-network:
    driver: bridge
