#!/bin/bash

# Script to auto-update the knowledge base with current project state
# This script should be run on git hooks or CI/CD pipelines

echo "🔄 Updating Knowledge Base..."

# Get current project structure
echo "📁 Generating current project tree..."
TREE_OUTPUT=$(tree -I 'node_modules|.git|*.log|*.tmp|dist|build' -a)

# Get current git status
echo "📊 Getting git status..."
GIT_STATUS=$(git status --porcelain)
GIT_BRANCH=$(git branch --show-current)
GIT_LAST_COMMIT=$(git log -1 --pretty=format:'%h - %s (%an, %ar)')

# Get package.json info
echo "📦 Extracting package.json info..."
if [ -f "package.json" ]; then
    PROJECT_NAME=$(node -p "require('./package.json').name")
    PROJECT_VERSION=$(node -p "require('./package.json').version")
    DEPENDENCIES_COUNT=$(node -p "Object.keys(require('./package.json').dependencies || {}).length")
    DEV_DEPENDENCIES_COUNT=$(node -p "Object.keys(require('./package.json').devDependencies || {}).length")
fi

# Count files and directories
FILES_COUNT=$(find . -type f -not -path './node_modules/*' -not -path './.git/*' | wc -l | tr -d ' ')
DIRS_COUNT=$(find . -type d -not -path './node_modules/*' -not -path './.git/*' | wc -l | tr -d ' ')

# Count database migrations
MIGRATIONS_COUNT=$(find ./database/migrations -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')

# Count models
MODELS_COUNT=$(find ./app/models -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')

# Update timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Create the updated section for KNOWLEDGE_BASE.md
cat > /tmp/kb_update.md << EOF

## Project Status (Auto-Updated)

**Last Update**: $TIMESTAMP
**Git Branch**: $GIT_BRANCH
**Last Commit**: $GIT_LAST_COMMIT

### 📊 Project Metrics
- **Files**: $FILES_COUNT files, $DIRS_COUNT directories
- **Dependencies**: $DEPENDENCIES_COUNT production, $DEV_DEPENDENCIES_COUNT development
- **Database**: $MIGRATIONS_COUNT migrations, $MODELS_COUNT models
- **Version**: $PROJECT_VERSION

### 🌳 Current Project Structure

\`\`\`
$TREE_OUTPUT
\`\`\`

### 🔄 Git Status

\`\`\`
Current branch: $GIT_BRANCH
$GIT_STATUS
\`\`\`

---
*Auto-generated by scripts/update-knowledge-base.sh*
EOF

# Check if KNOWLEDGE_BASE.md exists in the new location
KNOWLEDGE_BASE_PATH="docs/architecture/KNOWLEDGE_BASE.md"

if [ -f "$KNOWLEDGE_BASE_PATH" ]; then
    # Remove old auto-updated section if it exists
    sed '/## Project Status (Auto-Updated)/,/\*Auto-generated by scripts\/update-knowledge-base\.sh\*/d' "$KNOWLEDGE_BASE_PATH" > /tmp/kb_clean.md

    # Append new section
    cat /tmp/kb_clean.md /tmp/kb_update.md > "$KNOWLEDGE_BASE_PATH"

    echo "✅ Knowledge Base updated successfully at $KNOWLEDGE_BASE_PATH!"
else
    echo "❌ $KNOWLEDGE_BASE_PATH not found!"
    exit 1
fi

# Cleanup
rm -f /tmp/kb_update.md /tmp/kb_clean.md

echo "🎉 Knowledge Base auto-update completed!"